In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

path = "/content/drive/MyDrive/datasetColab"
print(os.listdir(path))

['data_csv.cancer_files', '1_CancerGov_QA', 'archive (13)', 'cancer_dataset.csv', 'cancer_dataset2.csv', 'final_dataset.csv', 'dataset3_clean.csv', 'dataset3_clean_final.csv', 'cancer_dataset_clean.csv', 'cancer_dataset2_clean.csv', 'final_dataset_clean.csv', 'dataset3_clean_clean.csv', 'dataset3_clean_final_clean.csv', 'cancer_dataset_clean_clean.csv', 'cancer_dataset2_clean_clean.csv', 'final_dataset_clean_clean.csv', 'dataset3_clean_clean_clean.csv', 'dataset3_clean_final_clean_clean.csv', 'cancer_dataset_clean_clean_clean.csv', 'cancer_dataset2_clean_clean_clean.csv', 'final_dataset_clean_clean_clean.csv', 'dataset3_clean_clean_clean_clean.csv', 'dataset3_clean_final_clean_clean_clean.csv', 'cancer_dataset_clean_clean_clean_clean.csv', 'cancer_dataset2_clean_clean_clean_clean.csv', 'final_dataset_clean_clean_clean_clean.csv', 'dataset3_clean_clean_clean_clean_clean.csv', 'dataset3_clean_final_clean_clean_clean_clean.csv']

In [ ]:
import os

print(os.listdir("/content/drive/MyDrive/datasetColab/data_csv.cancer_files"))

['cancer_qa_dataset_1000.csv', 'cancer_qa_dataset_5000.csv', 'silk-hq-lutwos9z.css', 'code-block-m2vhenll.css', 'kt.png', 'index-ivzj8m6u.css', 'product-variants-ga945uk2.css', 'code-block-editor-pane-fzo1sbww.css', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png', 'root-mn12m92t.css', 'conversation-small-1rwf4ooe.css', 'writing-block-editor-j0pgo4i4.css', 'table-components-ca43bz4f.css', 'ansi-1f6vhsjh.css', 'bb140dcc-565b-4572-aa9e-53f02d96d04a.png', 'js', 'saved_resource.html', 'dataset.json', 'DATTASET.JSON', 'test-00000-of-00001-1fb925721582029b.parquet', 'train-00000-of-00001-c0696c2b7ee38eb5.parquet', 'test.csv', 'train.csv', 'conversaciones_cancer.json', 'conversaciones_cancer (2).json', 'conversaciones_cancer (3).json', 'Regenerated_Lung_Cancer_QA_Dataset.csv', 'train-00000-of-00001.parquet', 'bone_cancer_samples.csv', 'brain_tumour_samples.csv', 'breast_cancer_samples.csv', 'colon_cancer_samples.csv', 'gastric_cancer_samples.csv', 'kidney_cancer_samples.csv', 'lung_cancer_samples.csv', 'ovarian_cancer_samples.csv', 'prostate_cancer_samples.csv', 'skin_cancer_samples.csv', 'lung_cancer_clean_5K.jsonl', 'train-00002-of-00004.parquet', 'train-00003-of-00004.parquet', 'train-00000-of-00004.parquet', 'train-00000-of-00001 (3).parquet', 'train-00000-of-00001 (2).parquet', 'cancer-risk-factors.csv', 'cancer.csv', 'med.csv', 'inca-donnees-mco-10.2025.xlsx', 'inca-donnees-smr-10.2025.xlsx', 'inca-donnees-had-10.2025.xlsx', 'synthetic_structured.json', 'synthetic_unstructured.json', 'train-00000-of-00001 (6).parquet', 'generate_dataset.py', 'cancer_risk_factors_steps_moderate_burden.csv', 'cancer_risk_factors_steps_low_burden.csv', 'cancer_risk_factors_steps_high_burden.csv', 'cancer_treatment_patterns_high_burden.csv', 'cancer_treatment_patterns_low_burden.csv', 'cancer_treatment_patterns_moderate_burden.csv', 'cancer_stage_diagnosis_ssa_high_burden.csv', 'cancer_stage_diagnosis_ssa_low_burden.csv', 'cancer_stage_diagnosis_ssa_moderate_burden.csv', 'generate_dataset (2).py', 'cancer_survival_afcrn_high_burden.csv', 'cancer_survival_afcrn_low_burden.csv', 'cancer_survival_afcrn_moderate_burden.csv', 'dataset_infos.json', 'datad.csv', 'dataf1.csv', 'medquad.csv', 'data_csv.cancer_files', 'cancer_qa_dataset_1000.csv_clean', 'cancer_qa_dataset_5000.csv_clean', 'silk-hq-lutwos9z.css_clean', 'code-block-m2vhenll.css_clean', 'kt.png_clean', 'index-ivzj8m6u.css_clean', 'product-variants-ga945uk2.css_clean', 'code-block-editor-pane-fzo1sbww.css_clean', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png_clean', 'root-mn12m92t.css_clean', 'conversation-small-1rwf4ooe.css_clean', 'writing-block-editor-j0pgo4i4.css_clean', 'table-components-ca43bz4f.css_clean', 'ansi-1f6vhsjh.css_clean', 'bb140dcc-565b-4572-aa9e-53f02d96d04a.png_clean', 'js_clean', 'saved_resource.html_clean', 'dataset.json_clean', 'DATTASET.JSON_clean', 'test-00000-of-00001-1fb925721582029b.parquet_clean', 'train-00000-of-00001-c0696c2b7ee38eb5.parquet_clean', 'test.csv_clean', 'train.csv_clean', 'conversaciones_cancer.json_clean', 'conversaciones_cancer (2).json_clean', 'conversaciones_cancer (3).json_clean', 'Regenerated_Lung_Cancer_QA_Dataset.csv_clean', 'train-00000-of-00001.parquet_clean', 'bone_cancer_samples.csv_clean', 'brain_tumour_samples.csv_clean', 'breast_cancer_samples.csv_clean', 'colon_cancer_samples.csv_clean', 'gastric_cancer_samples.csv_clean', 'kidney_cancer_samples.csv_clean', 'lung_cancer_samples.csv_clean', 'ovarian_cancer_samples.csv_clean', 'prostate_cancer_samples.csv_clean', 'skin_cancer_samples.csv_clean', 'lung_cancer_clean_5K.jsonl_clean', 'train-00002-of-00004.parquet_clean', 'train-00003-of-00004.parquet_clean', 'train-00000-of-00001 (3).parquet_clean', 'train-00000-of-00001 (2).parquet_clean', 'cancer-risk-factors.csv_clean', 'cancer.csv_clean', 'med.csv_clean', 'inca-donnees-mco-10.2025.xlsx_clean', 'inca-donnees-smr-10.2025.xlsx_clean', 'inca-donnees-had-10.2025.xlsx_clean', 'synthetic_structured.json_clean', 'synthetic_unstructured.json_clean', 'train-00000-of-00001 (6).parquet_clean', 'generate_dataset.py_clean', 'cancer_risk_factors_steps_moderate_burden.csv_clean', 'cancer_risk_factors_steps_low_burden.csv_clean', 'cancer_risk_factors_steps_high_burden.csv_clean', 'cancer_treatment_patterns_high_burden.csv_clean', 'cancer_treatment_patterns_low_burden.csv_clean', 'cancer_treatment_patterns_moderate_burden.csv_clean', 'cancer_stage_diagnosis_ssa_high_burden.csv_clean', 'cancer_stage_diagnosis_ssa_low_burden.csv_clean', 'cancer_stage_diagnosis_ssa_moderate_burden.csv_clean', 'generate_dataset (2).py_clean', 'cancer_survival_afcrn_high_burden.csv_clean', 'cancer_survival_afcrn_low_burden.csv_clean', 'cancer_survival_afcrn_moderate_burden.csv_clean', 'dataset_infos.json_clean', 'datad.csv_clean', 'dataf1.csv_clean', 'medquad.csv_clean', 'cancer_qa_dataset_1000_clean.csv', 'cancer_qa_dataset_5000_clean.csv', 'silk-hq-lutwos9z_clean.txt', 'code-block-m2vhenll_clean.txt', 'kt_clean.txt', 'index-ivzj8m6u_clean.txt', 'product-variants-ga945uk2_clean.txt', 'code-block-editor-pane-fzo1sbww_clean.txt', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean.txt', 'root-mn12m92t_clean.txt', 'conversation-small-1rwf4ooe_clean.txt', 'writing-block-editor-j0pgo4i4_clean.txt', 'table-components-ca43bz4f_clean.txt', 'ansi-1f6vhsjh_clean.txt', 'bb140dcc-565b-4572-aa9e-53f02d96d04a_clean.txt', 'js_clean.txt', 'saved_resource_clean.txt', 'DATTASET_clean.txt', 'test-00000-of-00001-1fb925721582029b_clean.txt', 'train-00000-of-00001-c0696c2b7ee38eb5_clean.txt', 'test_clean.csv', 'train_clean.csv', 'conversaciones_cancer_clean.json', 'conversaciones_cancer (2)_clean.json', 'conversaciones_cancer (3)_clean.json', 'Regenerated_Lung_Cancer_QA_Dataset_clean.csv', 'train-00000-of-00001_clean.txt', 'bone_cancer_samples_clean.csv', 'brain_tumour_samples_clean.csv', 'breast_cancer_samples_clean.csv', 'colon_cancer_samples_clean.csv', 'gastric_cancer_samples_clean.csv', 'kidney_cancer_samples_clean.csv', 'lung_cancer_samples_clean.csv', 'ovarian_cancer_samples_clean.csv', 'prostate_cancer_samples_clean.csv', 'skin_cancer_samples_clean.csv', 'lung_cancer_clean_5K_clean.txt', 'train-00002-of-00004_clean.txt', 'train-00003-of-00004_clean.txt', 'train-00000-of-00004_clean.txt', 'train-00000-of-00001 (3)_clean.txt', 'train-00000-of-00001 (2)_clean.txt', 'cancer-risk-factors_clean.csv', 'cancer_clean.csv', 'med_clean.csv', 'inca-donnees-mco-10.2025_clean.txt', 'inca-donnees-smr-10.2025_clean.txt', 'inca-donnees-had-10.2025_clean.txt', 'synthetic_structured_clean.json', 'synthetic_unstructured_clean.json', 'train-00000-of-00001 (6)_clean.txt', 'generate_dataset_clean.txt', 'cancer_risk_factors_steps_moderate_burden_clean.csv', 'cancer_risk_factors_steps_low_burden_clean.csv', 'cancer_risk_factors_steps_high_burden_clean.csv', 'cancer_treatment_patterns_high_burden_clean.csv', 'cancer_treatment_patterns_low_burden_clean.csv', 'cancer_treatment_patterns_moderate_burden_clean.csv', 'cancer_stage_diagnosis_ssa_high_burden_clean.csv', 'cancer_stage_diagnosis_ssa_low_burden_clean.csv', 'cancer_stage_diagnosis_ssa_moderate_burden_clean.csv', 'generate_dataset (2)_clean.txt', 'cancer_survival_afcrn_high_burden_clean.csv', 'cancer_survival_afcrn_low_burden_clean.csv', 'cancer_survival_afcrn_moderate_burden_clean.csv', 'dataset_infos_clean.json', 'datad_clean.csv', 'dataf1_clean.csv', 'medquad_clean.csv', 'cancer_qa_dataset_1000_clean.txt', 'cancer_qa_dataset_5000_clean.txt', 'js_clean_clean.txt', 'dataset_clean.txt', 'test_clean.txt', 'train_clean.txt', 'conversaciones_cancer_clean.txt', 'conversaciones_cancer (2)_clean.txt', 'conversaciones_cancer (3)_clean.txt', 'Regenerated_Lung_Cancer_QA_Dataset_clean.txt', 'bone_cancer_samples_clean.txt', 'brain_tumour_samples_clean.txt', 'breast_cancer_samples_clean.txt', 'colon_cancer_samples_clean.txt', 'gastric_cancer_samples_clean.txt', 'kidney_cancer_samples_clean.txt', 'lung_cancer_samples_clean.txt', 'ovarian_cancer_samples_clean.txt', 'prostate_cancer_samples_clean.txt', 'skin_cancer_samples_clean.txt', 'cancer-risk-factors_clean.txt', 'cancer_clean.txt', 'med_clean.txt', 'synthetic_structured_clean.txt', 'synthetic_unstructured_clean.txt', 'cancer_risk_factors_steps_moderate_burden_clean.txt', 'cancer_risk_factors_steps_low_burden_clean.txt', 'cancer_risk_factors_steps_high_burden_clean.txt', 'cancer_treatment_patterns_high_burden_clean.txt', 'cancer_treatment_patterns_low_burden_clean.txt', 'cancer_treatment_patterns_moderate_burden_clean.txt', 'cancer_stage_diagnosis_ssa_high_burden_clean.txt', 'cancer_stage_diagnosis_ssa_low_burden_clean.txt', 'cancer_stage_diagnosis_ssa_moderate_burden_clean.txt', 'cancer_survival_afcrn_high_burden_clean.txt', 'cancer_survival_afcrn_low_burden_clean.txt', 'cancer_survival_afcrn_moderate_burden_clean.txt', 'dataset_infos_clean.txt', 'datad_clean.txt', 'dataf1_clean.txt', 'medquad_clean.txt', 'cancer_qa_dataset_1000_clean_clean.csv', 'cancer_qa_dataset_5000_clean_clean.csv', 'silk-hq-lutwos9z_clean_clean.txt', 'code-block-m2vhenll_clean_clean.txt', 'kt_clean_clean.txt', 'index-ivzj8m6u_clean_clean.txt', 'product-variants-ga945uk2_clean_clean.txt', 'code-block-editor-pane-fzo1sbww_clean_clean.txt', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean_clean.txt', 'root-mn12m92t_clean_clean.txt', 'conversation-small-1rwf4ooe_clean_clean.txt', 'writing-block-editor-j0pgo4i4_clean_clean.txt', 'table-components-ca43bz4f_clean_clean.txt', 'ansi-1f6vhsjh_clean_clean.txt', 'bb140dcc-565b-4572-aa9e-53f02d96d04a_clean_clean.txt', 'saved_resource_clean_clean.txt', 'DATTASET_clean_clean.txt', 'test-00000-of-00001-1fb925721582029b_clean_clean.txt', 'train-00000-of-00001-c0696c2b7ee38eb5_clean_clean.txt', 'test_clean_clean.csv', 'train_clean_clean.csv', 'conversaciones_cancer_clean_clean.json', 'conversaciones_cancer (2)_clean_clean.json', 'conversaciones_cancer (3)_clean_clean.json', 'Regenerated_Lung_Cancer_QA_Dataset_clean_clean.csv', 'train-00000-of-00001_clean_clean.txt', 'bone_cancer_samples_clean_clean.csv', 'brain_tumour_samples_clean_clean.csv', 'breast_cancer_samples_clean_clean.csv', 'colon_cancer_samples_clean_clean.csv', 'gastric_cancer_samples_clean_clean.csv', 'kidney_cancer_samples_clean_clean.csv', 'lung_cancer_samples_clean_clean.csv', 'ovarian_cancer_samples_clean_clean.csv', 'prostate_cancer_samples_clean_clean.csv', 'skin_cancer_samples_clean_clean.csv', 'lung_cancer_clean_5K_clean_clean.txt']

In [ ]:
print(os.listdir("/content/drive/MyDrive/datasetColab/1_CancerGov_QA"))

['0000019_2.xml', '0000032_1.xml', '0000025_2.xml', '0000036_2.xml', '0000006_5.xml', '0000019_3.xml', '0000019_5.xml', '0000022_1.xml', '0000006_4.xml', '0000027_4.xml', '0000024_2.xml', '0000036_3.xml', '0000004_5.xml', '0000021_1.xml', '0000037_4.xml', '0000003_4.xml', '0000013_3_4.xml', '0000026_1.xml', '0000026_3.xml', '0000024_4.xml', '0000013_3_2.xml', '0000007_5.xml', '0000006_9.xml', '0000036_1.xml', '0000003_5.xml', '0000001_7.xml', '0000032_4.xml', '0000013_2_2.xml', '0000004_4.xml', '0000037_2.xml', '0000030_1.xml', '0000023_1.xml', '0000028_4.xml', '0000016_1.xml', '0000005_2.xml', '0000018_1.xml', '0000024_1.xml', '0000024_6.xml', '0000014_1.xml', '0000034_1.xml', '0000024_7.xml', '0000006_7.xml', '0000003_3.xml', '0000003_1.xml', '0000007_1.xml', '0000024_3.xml', '0000001_2.xml', '0000007_4.xml', '0000027_2.xml', '0000028_2.xml', '0000026_2.xml', '0000025_1.xml', '0000031_2.xml', '0000028_3.xml', '0000021_2.xml', '0000043_1.xml', '0000001_3.xml', '0000009_2.xml', '0000004_1.xml', '0000032_2.xml', '0000013_2_1.xml', '0000027_5.xml', '0000007_3.xml', '0000033_1.xml', '0000013_1.xml', '0000013_2_6.xml', '0000004_3.xml', '0000028_5.xml', '0000014_4.xml', '0000004_6.xml', '0000028_1.xml', '0000001_5.xml', '0000001_6.xml', '0000007_2.xml', '0000027_3.xml', '0000037_1.xml', '0000006_8.xml', '0000004_7.xml', '0000003_6.xml', '0000010_1.xml', '0000020_1.xml', '0000004_2.xml', '0000005_1.xml', '0000013_3_1.xml', '0000039_1.xml', '0000006_2.xml', '0000041_1.xml', '0000001_4.xml', '0000019_1.xml', '0000006_3.xml', '0000024_8.xml', '0000013_2_5.xml', '0000027_1.xml', '0000032_3.xml', '0000001_1.xml', '0000017_1.xml', '0000013_3.xml', '0000014_2.xml', '0000035_1.xml', '0000040_1.xml', '0000019_4.xml', '0000009_1.xml', '0000024_9.xml', '0000037_3.xml', '0000024_10.xml', '0000014_3.xml', '0000015_1.xml', '0000013_3_3.xml', '0000006_6.xml', '0000013_2_3.xml', '0000003_2.xml', '0000006_1.xml', '0000013_2.xml', '0000031_1.xml', '0000024_5.xml', '0000013_2_4.xml', '0000019_2.xml_clean', '0000032_1.xml_clean', '0000025_2.xml_clean', '0000036_2.xml_clean', '0000006_5.xml_clean', '0000019_3.xml_clean', '0000019_5.xml_clean', '0000022_1.xml_clean', '0000006_4.xml_clean', '0000027_4.xml_clean', '0000024_2.xml_clean', '0000036_3.xml_clean', '0000004_5.xml_clean', '0000021_1.xml_clean', '0000037_4.xml_clean', '0000003_4.xml_clean', '0000013_3_4.xml_clean', '0000026_1.xml_clean', '0000026_3.xml_clean', '0000024_4.xml_clean', '0000013_3_2.xml_clean', '0000007_5.xml_clean', '0000006_9.xml_clean', '0000036_1.xml_clean', '0000003_5.xml_clean', '0000001_7.xml_clean', '0000032_4.xml_clean', '0000013_2_2.xml_clean', '0000004_4.xml_clean', '0000037_2.xml_clean', '0000030_1.xml_clean', '0000023_1.xml_clean', '0000028_4.xml_clean', '0000016_1.xml_clean', '0000005_2.xml_clean', '0000018_1.xml_clean', '0000024_1.xml_clean', '0000024_6.xml_clean', '0000014_1.xml_clean', '0000034_1.xml_clean', '0000024_7.xml_clean', '0000006_7.xml_clean', '0000003_3.xml_clean', '0000003_1.xml_clean', '0000007_1.xml_clean', '0000024_3.xml_clean', '0000001_2.xml_clean', '0000007_4.xml_clean', '0000027_2.xml_clean', '0000028_2.xml_clean', '0000026_2.xml_clean', '0000025_1.xml_clean', '0000031_2.xml_clean', '0000028_3.xml_clean', '0000021_2.xml_clean', '0000043_1.xml_clean', '0000001_3.xml_clean', '0000009_2.xml_clean', '0000004_1.xml_clean', '0000032_2.xml_clean', '0000013_2_1.xml_clean', '0000027_5.xml_clean', '0000007_3.xml_clean', '0000033_1.xml_clean', '0000013_1.xml_clean', '0000013_2_6.xml_clean', '0000004_3.xml_clean', '0000028_5.xml_clean', '0000014_4.xml_clean', '0000004_6.xml_clean', '0000028_1.xml_clean', '0000001_5.xml_clean', '0000001_6.xml_clean', '0000007_2.xml_clean', '0000027_3.xml_clean', '0000037_1.xml_clean', '0000006_8.xml_clean', '0000004_7.xml_clean', '0000003_6.xml_clean', '0000010_1.xml_clean', '0000020_1.xml_clean', '0000004_2.xml_clean', '0000005_1.xml_clean', '0000013_3_1.xml_clean', '0000039_1.xml_clean', '0000006_2.xml_clean', '0000041_1.xml_clean', '0000001_4.xml_clean', '0000019_1.xml_clean', '0000006_3.xml_clean', '0000024_8.xml_clean', '0000013_2_5.xml_clean', '0000027_1.xml_clean', '0000032_3.xml_clean', '0000001_1.xml_clean', '0000017_1.xml_clean', '0000013_3.xml_clean', '0000014_2.xml_clean', '0000035_1.xml_clean', '0000040_1.xml_clean', '0000019_4.xml_clean', '0000009_1.xml_clean', '0000024_9.xml_clean', '0000037_3.xml_clean', '0000024_10.xml_clean', '0000014_3.xml_clean', '0000015_1.xml_clean', '0000013_3_3.xml_clean', '0000006_6.xml_clean', '0000013_2_3.xml_clean', '0000003_2.xml_clean', '0000006_1.xml_clean', '0000013_2.xml_clean', '0000031_1.xml_clean', '0000024_5.xml_clean', '0000013_2_4.xml_clean', '0000019_2_clean.xml', '0000032_1_clean.xml', '0000025_2_clean.xml', '0000036_2_clean.xml', '0000006_5_clean.xml', '0000019_3_clean.xml', '0000019_5_clean.xml', '0000022_1_clean.xml', '0000006_4_clean.xml', '0000027_4_clean.xml', '0000024_2_clean.xml', '0000036_3_clean.xml', '0000004_5_clean.xml', '0000021_1_clean.xml', '0000037_4_clean.xml', '0000003_4_clean.xml', '0000013_3_4_clean.xml', '0000026_1_clean.xml', '0000026_3_clean.xml', '0000024_4_clean.xml', '0000013_3_2_clean.xml', '0000007_5_clean.xml', '0000006_9_clean.xml', '0000036_1_clean.xml', '0000003_5_clean.xml', '0000001_7_clean.xml', '0000032_4_clean.xml', '0000013_2_2_clean.xml', '0000004_4_clean.xml', '0000037_2_clean.xml', '0000030_1_clean.xml', '0000023_1_clean.xml', '0000028_4_clean.xml', '0000016_1_clean.xml', '0000005_2_clean.xml', '0000018_1_clean.xml', '0000024_1_clean.xml', '0000024_6_clean.xml', '0000014_1_clean.xml', '0000034_1_clean.xml', '0000024_7_clean.xml', '0000006_7_clean.xml', '0000003_3_clean.xml', '0000003_1_clean.xml', '0000007_1_clean.xml', '0000024_3_clean.xml', '0000001_2_clean.xml', '0000007_4_clean.xml', '0000027_2_clean.xml', '0000028_2_clean.xml', '0000026_2_clean.xml', '0000025_1_clean.xml', '0000031_2_clean.xml', '0000028_3_clean.xml', '0000021_2_clean.xml', '0000043_1_clean.xml', '0000001_3_clean.xml', '0000009_2_clean.xml', '0000004_1_clean.xml', '0000032_2_clean.xml', '0000013_2_1_clean.xml', '0000027_5_clean.xml', '0000007_3_clean.xml', '0000033_1_clean.xml', '0000013_1_clean.xml', '0000013_2_6_clean.xml', '0000004_3_clean.xml', '0000028_5_clean.xml', '0000014_4_clean.xml', '0000004_6_clean.xml', '0000028_1_clean.xml', '0000001_5_clean.xml', '0000001_6_clean.xml', '0000007_2_clean.xml', '0000027_3_clean.xml', '0000037_1_clean.xml', '0000006_8_clean.xml', '0000004_7_clean.xml', '0000003_6_clean.xml', '0000010_1_clean.xml', '0000020_1_clean.xml', '0000004_2_clean.xml', '0000005_1_clean.xml', '0000013_3_1_clean.xml', '0000039_1_clean.xml', '0000006_2_clean.xml', '0000041_1_clean.xml', '0000001_4_clean.xml', '0000019_1_clean.xml', '0000006_3_clean.xml', '0000024_8_clean.xml', '0000013_2_5_clean.xml', '0000027_1_clean.xml', '0000032_3_clean.xml', '0000001_1_clean.xml', '0000017_1_clean.xml', '0000013_3_clean.xml', '0000014_2_clean.xml', '0000035_1_clean.xml', '0000040_1_clean.xml', '0000019_4_clean.xml', '0000009_1_clean.xml', '0000024_9_clean.xml', '0000037_3_clean.xml', '0000024_10_clean.xml', '0000014_3_clean.xml', '0000015_1_clean.xml', '0000013_3_3_clean.xml', '0000006_6_clean.xml', '0000013_2_3_clean.xml', '0000003_2_clean.xml', '0000006_1_clean.xml', '0000013_2_clean.xml', '0000031_1_clean.xml', '0000024_5_clean.xml', '0000013_2_4_clean.xml', '0000019_2_clean.txt', '0000032_1_clean.txt', '0000025_2_clean.txt', '0000036_2_clean.txt', '0000006_5_clean.txt', '0000019_3_clean.txt', '0000019_5_clean.txt', '0000022_1_clean.txt', '0000006_4_clean.txt', '0000027_4_clean.txt', '0000024_2_clean.txt', '0000036_3_clean.txt', '0000004_5_clean.txt', '0000021_1_clean.txt', '0000037_4_clean.txt', '0000003_4_clean.txt', '0000013_3_4_clean.txt', '0000026_1_clean.txt', '0000026_3_clean.txt', '0000024_4_clean.txt', '0000013_3_2_clean.txt', '0000007_5_clean.txt', '0000006_9_clean.txt', '0000036_1_clean.txt', '0000003_5_clean.txt', '0000001_7_clean.txt', '0000032_4_clean.txt', '0000013_2_2_clean.txt', '0000004_4_clean.txt', '0000037_2_clean.txt', '0000030_1_clean.txt', '0000023_1_clean.txt', '0000028_4_clean.txt', '0000016_1_clean.txt', '0000005_2_clean.txt', '0000018_1_clean.txt', '0000024_1_clean.txt', '0000024_6_clean.txt', '0000014_1_clean.txt', '0000034_1_clean.txt', '0000024_7_clean.txt', '0000006_7_clean.txt', '0000003_3_clean.txt', '0000003_1_clean.txt', '0000007_1_clean.txt', '0000024_3_clean.txt', '0000001_2_clean.txt', '0000007_4_clean.txt', '0000027_2_clean.txt', '0000028_2_clean.txt', '0000026_2_clean.txt', '0000025_1_clean.txt', '0000031_2_clean.txt', '0000028_3_clean.txt', '0000021_2_clean.txt', '0000043_1_clean.txt', '0000001_3_clean.txt', '0000009_2_clean.txt', '0000004_1_clean.txt', '0000032_2_clean.txt', '0000013_2_1_clean.txt', '0000027_5_clean.txt', '0000007_3_clean.txt', '0000033_1_clean.txt', '0000013_1_clean.txt', '0000013_2_6_clean.txt', '0000004_3_clean.txt', '0000028_5_clean.txt', '0000014_4_clean.txt', '0000004_6_clean.txt', '0000028_1_clean.txt', '0000001_5_clean.txt', '0000001_6_clean.txt', '0000007_2_clean.txt', '0000027_3_clean.txt', '0000037_1_clean.txt', '0000006_8_clean.txt', '0000004_7_clean.txt', '0000003_6_clean.txt', '0000010_1_clean.txt', '0000020_1_clean.txt', '0000004_2_clean.txt', '0000005_1_clean.txt', '0000013_3_1_clean.txt', '0000039_1_clean.txt', '0000006_2_clean.txt', '0000041_1_clean.txt', '0000001_4_clean.txt', '0000019_1_clean.txt', '0000006_3_clean.txt', '0000024_8_clean.txt', '0000013_2_5_clean.txt', '0000027_1_clean.txt', '0000032_3_clean.txt', '0000001_1_clean.txt', '0000017_1_clean.txt', '0000013_3_clean.txt', '0000014_2_clean.txt', '0000035_1_clean.txt', '0000040_1_clean.txt', '0000019_4_clean.txt', '0000009_1_clean.txt', '0000024_9_clean.txt', '0000037_3_clean.txt', '0000024_10_clean.txt', '0000014_3_clean.txt', '0000015_1_clean.txt', '0000013_3_3_clean.txt', '0000006_6_clean.txt', '0000013_2_3_clean.txt', '0000003_2_clean.txt', '0000006_1_clean.txt', '0000013_2_clean.txt', '0000031_1_clean.txt', '0000024_5_clean.txt', '0000013_2_4_clean.txt']

In [ ]:
print(os.listdir("/content/drive/MyDrive/datasetColab/archive (13)"))

['CancerQA_clean.xls', 'valid.csv', 'Me-EXCL_evaluation_cancer_dataset.csv', 'breast%20cancer%20information%20for%20chatbot.csv', 'The_Cancer_data_set_V3.csv', 'CancerQA_clean.xls_clean', 'valid.csv_clean', 'Me-EXCL_evaluation_cancer_dataset.csv_clean', 'breast%20cancer%20information%20for%20chatbot.csv_clean', 'The_Cancer_data_set_V3.csv_clean', 'CancerQA_clean_clean.txt', 'valid_clean.csv', 'Me-EXCL_evaluation_cancer_dataset_clean.csv', 'breast%20cancer%20information%20for%20chatbot_clean.csv', 'The_Cancer_data_set_V3_clean.csv', 'valid_clean.txt', 'Me-EXCL_evaluation_cancer_dataset_clean.txt', 'breast%20cancer%20information%20for%20chatbot_clean.txt', 'The_Cancer_data_set_V3_clean.txt']

In [ ]:
import os
import pandas as pd

folder = "/content/drive/MyDrive/datasetColab/data_csv.cancer_files"

dataframes = []

for file in os.listdir(folder):
    if file.endswith(".csv"):
        path = os.path.join(folder, file)
        try:
            df = pd.read_csv(path, encoding="latin1", on_bad_lines="skip")
            dataframes.append(df)
            print("fichier chargé :", file)
        except:
            print("erreur fichier :", file)

data = pd.concat(dataframes, ignore_index=True)

print("Total lignes :", len(data))
data.head()

fichier chargé : cancer_qa_dataset_1000.csv
fichier chargé : cancer_qa_dataset_5000.csv
fichier chargé : test.csv
fichier chargé : train.csv
fichier chargé : Regenerated_Lung_Cancer_QA_Dataset.csv
fichier chargé : bone_cancer_samples.csv
fichier chargé : brain_tumour_samples.csv
fichier chargé : breast_cancer_samples.csv
fichier chargé : colon_cancer_samples.csv
fichier chargé : gastric_cancer_samples.csv
fichier chargé : kidney_cancer_samples.csv
fichier chargé : lung_cancer_samples.csv
fichier chargé : ovarian_cancer_samples.csv
fichier chargé : prostate_cancer_samples.csv
fichier chargé : skin_cancer_samples.csv
fichier chargé : cancer-risk-factors.csv
fichier chargé : cancer.csv
fichier chargé : med.csv
fichier chargé : cancer_risk_factors_steps_moderate_burden.csv
fichier chargé : cancer_risk_factors_steps_low_burden.csv
fichier chargé : cancer_risk_factors_steps_high_burden.csv
fichier chargé : cancer_treatment_patterns_high_burden.csv
fichier chargé : cancer_treatment_patterns_low_burden.csv
fichier chargé : cancer_treatment_patterns_moderate_burden.csv
fichier chargé : cancer_stage_diagnosis_ssa_high_burden.csv
fichier chargé : cancer_stage_diagnosis_ssa_low_burden.csv
fichier chargé : cancer_stage_diagnosis_ssa_moderate_burden.csv
fichier chargé : cancer_survival_afcrn_high_burden.csv
fichier chargé : cancer_survival_afcrn_low_burden.csv
fichier chargé : cancer_survival_afcrn_moderate_burden.csv
fichier chargé : datad.csv
fichier chargé : dataf1.csv
fichier chargé : medquad.csv
fichier chargé : cancer_qa_dataset_1000_clean.csv
fichier chargé : cancer_qa_dataset_5000_clean.csv
fichier chargé : test_clean.csv
fichier chargé : train_clean.csv
fichier chargé : Regenerated_Lung_Cancer_QA_Dataset_clean.csv
fichier chargé : bone_cancer_samples_clean.csv
fichier chargé : brain_tumour_samples_clean.csv
fichier chargé : breast_cancer_samples_clean.csv
fichier chargé : colon_cancer_samples_clean.csv
fichier chargé : gastric_cancer_samples_clean.csv
fichier chargé : kidney_cancer_samples_clean.csv
fichier chargé : lung_cancer_samples_clean.csv
fichier chargé : ovarian_cancer_samples_clean.csv
fichier chargé : prostate_cancer_samples_clean.csv
fichier chargé : skin_cancer_samples_clean.csv
fichier chargé : cancer-risk-factors_clean.csv
fichier chargé : cancer_clean.csv
fichier chargé : med_clean.csv
fichier chargé : cancer_risk_factors_steps_moderate_burden_clean.csv
fichier chargé : cancer_risk_factors_steps_low_burden_clean.csv
fichier chargé : cancer_risk_factors_steps_high_burden_clean.csv
fichier chargé : cancer_treatment_patterns_high_burden_clean.csv
fichier chargé : cancer_treatment_patterns_low_burden_clean.csv
fichier chargé : cancer_treatment_patterns_moderate_burden_clean.csv
fichier chargé : cancer_stage_diagnosis_ssa_high_burden_clean.csv
fichier chargé : cancer_stage_diagnosis_ssa_low_burden_clean.csv
fichier chargé : cancer_stage_diagnosis_ssa_moderate_burden_clean.csv
fichier chargé : cancer_survival_afcrn_high_burden_clean.csv
fichier chargé : cancer_survival_afcrn_low_burden_clean.csv
fichier chargé : cancer_survival_afcrn_moderate_burden_clean.csv
fichier chargé : datad_clean.csv
fichier chargé : dataf1_clean.csv
fichier chargé : medquad_clean.csv
fichier chargé : cancer_qa_dataset_1000_clean_clean.csv
fichier chargé : cancer_qa_dataset_5000_clean_clean.csv
fichier chargé : test_clean_clean.csv
fichier chargé : train_clean_clean.csv
fichier chargé : Regenerated_Lung_Cancer_QA_Dataset_clean_clean.csv
fichier chargé : bone_cancer_samples_clean_clean.csv
fichier chargé : brain_tumour_samples_clean_clean.csv
fichier chargé : breast_cancer_samples_clean_clean.csv
fichier chargé : colon_cancer_samples_clean_clean.csv
fichier chargé : gastric_cancer_samples_clean_clean.csv
fichier chargé : kidney_cancer_samples_clean_clean.csv
fichier chargé : lung_cancer_samples_clean_clean.csv
fichier chargé : ovarian_cancer_samples_clean_clean.csv
fichier chargé : prostate_cancer_samples_clean_clean.csv
fichier chargé : skin_cancer_samples_clean_clean.csv
Total lignes : 506180

,question,answer,posts,predicted,intensity,input,output,Unnamed: 0,Cancer Type,PMID,...,vital_status_5yr,survival_months,cause_of_death,Question,Answer_choice,Correct_or_not,ï»¿Radiation Physics Questions for ChatGPT,source,focus_area,Ã¯Â»Â¿Radiation Physics Questions for ChatGPT
0,What is lung cancer?,Lung cancer is a disease in which abnormal cel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,What causes breast cancer?,Breast cancer may develop because of genetic m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,What are the symptoms of prostate cancer?,Symptoms of prostate cancer can vary depending...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,How is colon cancer diagnosed?,Doctors diagnose colon cancer using a combinat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,What treatments are available for rectal cancer?,Treatment for rectal cancer depends on the sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import os

folder = "/content/drive/MyDrive/datasetColab"

for root, dirs, files in os.walk(folder):
    print("DOSSIER :", root)

    for d in dirs:
        print("   📁", d)

    for f in files:
        print("   📄", f)

    print("-------------------")

DOSSIER : /content/drive/MyDrive/datasetColab
   📁 data_csv.cancer_files
   📁 1_CancerGov_QA
   📁 archive (13)
   📄 cancer_dataset.csv
   📄 cancer_dataset2.csv
   📄 final_dataset.csv
   📄 dataset3_clean.csv
   📄 dataset3_clean_final.csv
   📄 cancer_dataset_clean.csv
   📄 cancer_dataset2_clean.csv
   📄 final_dataset_clean.csv
   📄 dataset3_clean_clean.csv
   📄 dataset3_clean_final_clean.csv
   📄 cancer_dataset_clean_clean.csv
   📄 cancer_dataset2_clean_clean.csv
   📄 final_dataset_clean_clean.csv
   📄 dataset3_clean_clean_clean.csv
   📄 dataset3_clean_final_clean_clean.csv
   📄 cancer_dataset_clean_clean_clean.csv
   📄 cancer_dataset2_clean_clean_clean.csv
   📄 final_dataset_clean_clean_clean.csv
   📄 dataset3_clean_clean_clean_clean.csv
   📄 dataset3_clean_final_clean_clean_clean.csv
-------------------
DOSSIER : /content/drive/MyDrive/datasetColab/data_csv.cancer_files
   📁 data_csv.cancer_files
   📄 cancer_qa_dataset_1000.csv
   📄 cancer_qa_dataset_5000.csv
   📄 silk-hq-lutwos9z.css
   📄 code-block-m2vhenll.css
   📄 kt.png
   📄 index-ivzj8m6u.css
   📄 product-variants-ga945uk2.css
   📄 code-block-editor-pane-fzo1sbww.css
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png
   📄 root-mn12m92t.css
   📄 conversation-small-1rwf4ooe.css
   📄 writing-block-editor-j0pgo4i4.css
   📄 table-components-ca43bz4f.css
   📄 ansi-1f6vhsjh.css
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a.png
   📄 js
   📄 saved_resource.html
   📄 dataset.json
   📄 DATTASET.JSON
   📄 test-00000-of-00001-1fb925721582029b.parquet
   📄 train-00000-of-00001-c0696c2b7ee38eb5.parquet
   📄 test.csv
   📄 train.csv
   📄 conversaciones_cancer.json
   📄 conversaciones_cancer (2).json
   📄 conversaciones_cancer (3).json
   📄 Regenerated_Lung_Cancer_QA_Dataset.csv
   📄 train-00000-of-00001.parquet
   📄 bone_cancer_samples.csv
   📄 brain_tumour_samples.csv
   📄 breast_cancer_samples.csv
   📄 colon_cancer_samples.csv
   📄 gastric_cancer_samples.csv
   📄 kidney_cancer_samples.csv
   📄 lung_cancer_samples.csv
   📄 ovarian_cancer_samples.csv
   📄 prostate_cancer_samples.csv
   📄 skin_cancer_samples.csv
   📄 lung_cancer_clean_5K.jsonl
   📄 train-00002-of-00004.parquet
   📄 train-00003-of-00004.parquet
   📄 train-00000-of-00004.parquet
   📄 train-00000-of-00001 (3).parquet
   📄 train-00000-of-00001 (2).parquet
   📄 cancer-risk-factors.csv
   📄 cancer.csv
   📄 med.csv
   📄 inca-donnees-mco-10.2025.xlsx
   📄 inca-donnees-smr-10.2025.xlsx
   📄 inca-donnees-had-10.2025.xlsx
   📄 synthetic_structured.json
   📄 synthetic_unstructured.json
   📄 train-00000-of-00001 (6).parquet
   📄 generate_dataset.py
   📄 cancer_risk_factors_steps_moderate_burden.csv
   📄 cancer_risk_factors_steps_low_burden.csv
   📄 cancer_risk_factors_steps_high_burden.csv
   📄 cancer_treatment_patterns_high_burden.csv
   📄 cancer_treatment_patterns_low_burden.csv
   📄 cancer_treatment_patterns_moderate_burden.csv
   📄 cancer_stage_diagnosis_ssa_high_burden.csv
   📄 cancer_stage_diagnosis_ssa_low_burden.csv
   📄 cancer_stage_diagnosis_ssa_moderate_burden.csv
   📄 generate_dataset (2).py
   📄 cancer_survival_afcrn_high_burden.csv
   📄 cancer_survival_afcrn_low_burden.csv
   📄 cancer_survival_afcrn_moderate_burden.csv
   📄 dataset_infos.json
   📄 datad.csv
   📄 dataf1.csv
   📄 medquad.csv
   📄 cancer_qa_dataset_1000.csv_clean
   📄 cancer_qa_dataset_5000.csv_clean
   📄 silk-hq-lutwos9z.css_clean
   📄 code-block-m2vhenll.css_clean
   📄 kt.png_clean
   📄 index-ivzj8m6u.css_clean
   📄 product-variants-ga945uk2.css_clean
   📄 code-block-editor-pane-fzo1sbww.css_clean
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png_clean
   📄 root-mn12m92t.css_clean
   📄 conversation-small-1rwf4ooe.css_clean
   📄 writing-block-editor-j0pgo4i4.css_clean
   📄 table-components-ca43bz4f.css_clean
   📄 ansi-1f6vhsjh.css_clean
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a.png_clean
   📄 js_clean
   📄 saved_resource.html_clean
   📄 dataset.json_clean
   📄 DATTASET.JSON_clean
   📄 test-00000-of-00001-1fb925721582029b.parquet_clean
   📄 train-00000-of-00001-c0696c2b7ee38eb5.parquet_clean
   📄 test.csv_clean
   📄 train.csv_clean
   📄 conversaciones_cancer.json_clean
   📄 conversaciones_cancer (2).json_clean
   📄 conversaciones_cancer (3).json_clean
   📄 Regenerated_Lung_Cancer_QA_Dataset.csv_clean
   📄 train-00000-of-00001.parquet_clean
   📄 bone_cancer_samples.csv_clean
   📄 brain_tumour_samples.csv_clean
   📄 breast_cancer_samples.csv_clean
   📄 colon_cancer_samples.csv_clean
   📄 gastric_cancer_samples.csv_clean
   📄 kidney_cancer_samples.csv_clean
   📄 lung_cancer_samples.csv_clean
   📄 ovarian_cancer_samples.csv_clean
   📄 prostate_cancer_samples.csv_clean
   📄 skin_cancer_samples.csv_clean
   📄 lung_cancer_clean_5K.jsonl_clean
   📄 train-00002-of-00004.parquet_clean
   📄 train-00003-of-00004.parquet_clean
   📄 train-00000-of-00001 (3).parquet_clean
   📄 train-00000-of-00001 (2).parquet_clean
   📄 cancer-risk-factors.csv_clean
   📄 cancer.csv_clean
   📄 med.csv_clean
   📄 inca-donnees-mco-10.2025.xlsx_clean
   📄 inca-donnees-smr-10.2025.xlsx_clean
   📄 inca-donnees-had-10.2025.xlsx_clean
   📄 synthetic_structured.json_clean
   📄 synthetic_unstructured.json_clean
   📄 train-00000-of-00001 (6).parquet_clean
   📄 generate_dataset.py_clean
   📄 cancer_risk_factors_steps_moderate_burden.csv_clean
   📄 cancer_risk_factors_steps_low_burden.csv_clean
   📄 cancer_risk_factors_steps_high_burden.csv_clean
   📄 cancer_treatment_patterns_high_burden.csv_clean
   📄 cancer_treatment_patterns_low_burden.csv_clean
   📄 cancer_treatment_patterns_moderate_burden.csv_clean
   📄 cancer_stage_diagnosis_ssa_high_burden.csv_clean
   📄 cancer_stage_diagnosis_ssa_low_burden.csv_clean
   📄 cancer_stage_diagnosis_ssa_moderate_burden.csv_clean
   📄 generate_dataset (2).py_clean
   📄 cancer_survival_afcrn_high_burden.csv_clean
   📄 cancer_survival_afcrn_low_burden.csv_clean
   📄 cancer_survival_afcrn_moderate_burden.csv_clean
   📄 dataset_infos.json_clean
   📄 datad.csv_clean
   📄 dataf1.csv_clean
   📄 medquad.csv_clean
   📄 cancer_qa_dataset_1000_clean.csv
   📄 cancer_qa_dataset_5000_clean.csv
   📄 silk-hq-lutwos9z_clean.txt
   📄 code-block-m2vhenll_clean.txt
   📄 kt_clean.txt
   📄 index-ivzj8m6u_clean.txt
   📄 product-variants-ga945uk2_clean.txt
   📄 code-block-editor-pane-fzo1sbww_clean.txt
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean.txt
   📄 root-mn12m92t_clean.txt
   📄 conversation-small-1rwf4ooe_clean.txt
   📄 writing-block-editor-j0pgo4i4_clean.txt
   📄 table-components-ca43bz4f_clean.txt
   📄 ansi-1f6vhsjh_clean.txt
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a_clean.txt
   📄 js_clean.txt
   📄 saved_resource_clean.txt
   📄 DATTASET_clean.txt
   📄 test-00000-of-00001-1fb925721582029b_clean.txt
   📄 train-00000-of-00001-c0696c2b7ee38eb5_clean.txt
   📄 test_clean.csv
   📄 train_clean.csv
   📄 conversaciones_cancer_clean.json
   📄 conversaciones_cancer (2)_clean.json
   📄 conversaciones_cancer (3)_clean.json
   📄 Regenerated_Lung_Cancer_QA_Dataset_clean.csv
   📄 train-00000-of-00001_clean.txt
   📄 bone_cancer_samples_clean.csv
   📄 brain_tumour_samples_clean.csv
   📄 breast_cancer_samples_clean.csv
   📄 colon_cancer_samples_clean.csv
   📄 gastric_cancer_samples_clean.csv
   📄 kidney_cancer_samples_clean.csv
   📄 lung_cancer_samples_clean.csv
   📄 ovarian_cancer_samples_clean.csv
   📄 prostate_cancer_samples_clean.csv
   📄 skin_cancer_samples_clean.csv
   📄 lung_cancer_clean_5K_clean.txt
   📄 train-00002-of-00004_clean.txt
   📄 train-00003-of-00004_clean.txt
   📄 train-00000-of-00004_clean.txt
   📄 train-00000-of-00001 (3)_clean.txt
   📄 train-00000-of-00001 (2)_clean.txt
   📄 cancer-risk-factors_clean.csv
   📄 cancer_clean.csv
   📄 med_clean.csv
   📄 inca-donnees-mco-10.2025_clean.txt
   📄 inca-donnees-smr-10.2025_clean.txt
   📄 inca-donnees-had-10.2025_clean.txt
   📄 synthetic_structured_clean.json
   📄 synthetic_unstructured_clean.json
   📄 train-00000-of-00001 (6)_clean.txt
   📄 generate_dataset_clean.txt
   📄 cancer_risk_factors_steps_moderate_burden_clean.csv
   📄 cancer_risk_factors_steps_low_burden_clean.csv
   📄 cancer_risk_factors_steps_high_burden_clean.csv
   📄 cancer_treatment_patterns_high_burden_clean.csv
   📄 cancer_treatment_patterns_low_burden_clean.csv
   📄 cancer_treatment_patterns_moderate_burden_clean.csv
   📄 cancer_stage_diagnosis_ssa_high_burden_clean.csv
   📄 cancer_stage_diagnosis_ssa_low_burden_clean.csv
   📄 cancer_stage_diagnosis_ssa_moderate_burden_clean.csv
   📄 generate_dataset (2)_clean.txt
   📄 cancer_survival_afcrn_high_burden_clean.csv
   📄 cancer_survival_afcrn_low_burden_clean.csv
   📄 cancer_survival_afcrn_moderate_burden_clean.csv
   📄 dataset_infos_clean.json
   📄 datad_clean.csv
   📄 dataf1_clean.csv
   📄 medquad_clean.csv
   📄 cancer_qa_dataset_1000_clean.txt
   📄 cancer_qa_dataset_5000_clean.txt
   📄 js_clean_clean.txt
   📄 dataset_clean.txt
   📄 test_clean.txt
   📄 train_clean.txt
   📄 conversaciones_cancer_clean.txt
   📄 conversaciones_cancer (2)_clean.txt
   📄 conversaciones_cancer (3)_clean.txt
   📄 Regenerated_Lung_Cancer_QA_Dataset_clean.txt
   📄 bone_cancer_samples_clean.txt
   📄 brain_tumour_samples_clean.txt
   📄 breast_cancer_samples_clean.txt
   📄 colon_cancer_samples_clean.txt
   📄 gastric_cancer_samples_clean.txt
   📄 kidney_cancer_samples_clean.txt
   📄 lung_cancer_samples_clean.txt
   📄 ovarian_cancer_samples_clean.txt
   📄 prostate_cancer_samples_clean.txt
   📄 skin_cancer_samples_clean.txt
   📄 cancer-risk-factors_clean.txt
   📄 cancer_clean.txt
   📄 med_clean.txt
   📄 synthetic_structured_clean.txt
   📄 synthetic_unstructured_clean.txt
   📄 cancer_risk_factors_steps_moderate_burden_clean.txt
   📄 cancer_risk_factors_steps_low_burden_clean.txt
   📄 cancer_risk_factors_steps_high_burden_clean.txt
   📄 cancer_treatment_patterns_high_burden_clean.txt
   📄 cancer_treatment_patterns_low_burden_clean.txt
   📄 cancer_treatment_patterns_moderate_burden_clean.txt
   📄 cancer_stage_diagnosis_ssa_high_burden_clean.txt
   📄 cancer_stage_diagnosis_ssa_low_burden_clean.txt
   📄 cancer_stage_diagnosis_ssa_moderate_burden_clean.txt
   📄 cancer_survival_afcrn_high_burden_clean.txt
   📄 cancer_survival_afcrn_low_burden_clean.txt
   📄 cancer_survival_afcrn_moderate_burden_clean.txt
   📄 dataset_infos_clean.txt
   📄 datad_clean.txt
   📄 dataf1_clean.txt
   📄 medquad_clean.txt
   📄 cancer_qa_dataset_1000_clean_clean.csv
   📄 cancer_qa_dataset_5000_clean_clean.csv
   📄 silk-hq-lutwos9z_clean_clean.txt
   📄 code-block-m2vhenll_clean_clean.txt
   📄 kt_clean_clean.txt
   📄 index-ivzj8m6u_clean_clean.txt
   📄 product-variants-ga945uk2_clean_clean.txt
   📄 code-block-editor-pane-fzo1sbww_clean_clean.txt
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean_clean.txt
   📄 root-mn12m92t_clean_clean.txt
   📄 conversation-small-1rwf4ooe_clean_clean.txt
   📄 writing-block-editor-j0pgo4i4_clean_clean.txt
   📄 table-components-ca43bz4f_clean_clean.txt
   📄 ansi-1f6vhsjh_clean_clean.txt
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a_clean_clean.txt
   📄 saved_resource_clean_clean.txt
   📄 DATTASET_clean_clean.txt
   📄 test-00000-of-00001-1fb925721582029b_clean_clean.txt
   📄 train-00000-of-00001-c0696c2b7ee38eb5_clean_clean.txt
   📄 test_clean_clean.csv
   📄 train_clean_clean.csv
   📄 conversaciones_cancer_clean_clean.json
   📄 conversaciones_cancer (2)_clean_clean.json
   📄 conversaciones_cancer (3)_clean_clean.json
   📄 Regenerated_Lung_Cancer_QA_Dataset_clean_clean.csv
   📄 train-00000-of-00001_clean_clean.txt
   📄 bone_cancer_samples_clean_clean.csv
   📄 brain_tumour_samples_clean_clean.csv
   📄 breast_cancer_samples_clean_clean.csv
   📄 colon_cancer_samples_clean_clean.csv
   📄 gastric_cancer_samples_clean_clean.csv
   📄 kidney_cancer_samples_clean_clean.csv
   📄 lung_cancer_samples_clean_clean.csv
   📄 ovarian_cancer_samples_clean_clean.csv
   📄 prostate_cancer_samples_clean_clean.csv
   📄 skin_cancer_samples_clean_clean.csv
   📄 lung_cancer_clean_5K_clean_clean.txt
-------------------
DOSSIER : /content/drive/MyDrive/datasetColab/data_csv.cancer_files/data_csv.cancer_files
   📄 cancer_qa_dataset_1000.csv
   📄 cancer_qa_dataset_5000.csv
   📄 table-components-ca43bz4f.css
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png
   📄 conversation-small-1rwf4ooe.css
   📄 index-ivzj8m6u.css
   📄 root-mn12m92t.css
   📄 product-variants-ga945uk2.css
   📄 silk-hq-lutwos9z.css
   📄 code-block-editor-pane-fzo1sbww.css
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a.png
   📄 kt.png
   📄 ansi-1f6vhsjh.css
   📄 writing-block-editor-j0pgo4i4.css
   📄 code-block-m2vhenll.css
   📄 js
   📄 saved_resource.html
   📄 dataset.json
   📄 DATTASET.JSON
   📄 test-00000-of-00001-1fb925721582029b.parquet
   📄 train-00000-of-00001-c0696c2b7ee38eb5.parquet
   📄 test.csv
   📄 conversaciones_cancer.json
   📄 conversaciones_cancer (2).json
   📄 conversaciones_cancer (3).json
   📄 Regenerated_Lung_Cancer_QA_Dataset.csv
   📄 train-00000-of-00001.parquet
   📄 bone_cancer_samples.csv
   📄 brain_tumour_samples.csv
   📄 breast_cancer_samples.csv
   📄 colon_cancer_samples.csv
   📄 gastric_cancer_samples.csv
   📄 kidney_cancer_samples.csv
   📄 lung_cancer_samples.csv
   📄 ovarian_cancer_samples.csv
   📄 prostate_cancer_samples.csv
   📄 skin_cancer_samples.csv
   📄 lung_cancer_clean_5K.jsonl
   📄 train-00000-of-00004.parquet
   📄 train-00000-of-00001 (3).parquet
   📄 train-00000-of-00001 (2).parquet
   📄 cancer-risk-factors.csv
   📄 cancer.csv
   📄 med.csv
   📄 inca-donnees-mco-10.2025.xlsx
   📄 inca-donnees-smr-10.2025.xlsx
   📄 inca-donnees-had-10.2025.xlsx
   📄 synthetic_structured.json
   📄 synthetic_unstructured.json
   📄 train-00000-of-00001 (6).parquet
   📄 generate_dataset.py
   📄 cancer_risk_factors_steps_moderate_burden.csv
   📄 cancer_risk_factors_steps_low_burden.csv
   📄 cancer_risk_factors_steps_high_burden.csv
   📄 cancer_treatment_patterns_high_burden.csv
   📄 cancer_treatment_patterns_low_burden.csv
   📄 cancer_treatment_patterns_moderate_burden.csv
   📄 cancer_stage_diagnosis_ssa_high_burden.csv
   📄 cancer_stage_diagnosis_ssa_low_burden.csv
   📄 cancer_stage_diagnosis_ssa_moderate_burden.csv
   📄 generate_dataset (2).py
   📄 cancer_survival_afcrn_high_burden.csv
   📄 cancer_survival_afcrn_low_burden.csv
   📄 cancer_survival_afcrn_moderate_burden.csv
   📄 dataset_infos.json
   📄 datad.csv
   📄 dataf1.csv
   📄 medquad.csv
   📄 cancer_qa_dataset_1000.csv_clean
   📄 cancer_qa_dataset_5000.csv_clean
   📄 table-components-ca43bz4f.css_clean
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png_clean
   📄 conversation-small-1rwf4ooe.css_clean
   📄 index-ivzj8m6u.css_clean
   📄 root-mn12m92t.css_clean
   📄 product-variants-ga945uk2.css_clean
   📄 silk-hq-lutwos9z.css_clean
   📄 code-block-editor-pane-fzo1sbww.css_clean
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a.png_clean
   📄 kt.png_clean
   📄 ansi-1f6vhsjh.css_clean
   📄 writing-block-editor-j0pgo4i4.css_clean
   📄 code-block-m2vhenll.css_clean
   📄 js_clean
   📄 saved_resource.html_clean
   📄 dataset.json_clean
   📄 DATTASET.JSON_clean
   📄 test-00000-of-00001-1fb925721582029b.parquet_clean
   📄 train-00000-of-00001-c0696c2b7ee38eb5.parquet_clean
   📄 test.csv_clean
   📄 conversaciones_cancer.json_clean
   📄 conversaciones_cancer (2).json_clean
   📄 conversaciones_cancer (3).json_clean
   📄 Regenerated_Lung_Cancer_QA_Dataset.csv_clean
   📄 train-00000-of-00001.parquet_clean
   📄 bone_cancer_samples.csv_clean
   📄 brain_tumour_samples.csv_clean
   📄 breast_cancer_samples.csv_clean
   📄 colon_cancer_samples.csv_clean
   📄 gastric_cancer_samples.csv_clean
   📄 kidney_cancer_samples.csv_clean
   📄 lung_cancer_samples.csv_clean
   📄 ovarian_cancer_samples.csv_clean
   📄 prostate_cancer_samples.csv_clean
   📄 skin_cancer_samples.csv_clean
   📄 lung_cancer_clean_5K.jsonl_clean
   📄 train-00000-of-00004.parquet_clean
   📄 train-00000-of-00001 (3).parquet_clean
   📄 train-00000-of-00001 (2).parquet_clean
   📄 cancer-risk-factors.csv_clean
   📄 cancer.csv_clean
   📄 med.csv_clean
   📄 inca-donnees-mco-10.2025.xlsx_clean
   📄 inca-donnees-smr-10.2025.xlsx_clean
   📄 inca-donnees-had-10.2025.xlsx_clean
   📄 synthetic_structured.json_clean
   📄 synthetic_unstructured.json_clean
   📄 train-00000-of-00001 (6).parquet_clean
   📄 generate_dataset.py_clean
   📄 cancer_risk_factors_steps_moderate_burden.csv_clean
   📄 cancer_risk_factors_steps_low_burden.csv_clean
   📄 cancer_risk_factors_steps_high_burden.csv_clean
   📄 cancer_treatment_patterns_high_burden.csv_clean
   📄 cancer_treatment_patterns_low_burden.csv_clean
   📄 cancer_treatment_patterns_moderate_burden.csv_clean
   📄 cancer_stage_diagnosis_ssa_high_burden.csv_clean
   📄 cancer_stage_diagnosis_ssa_low_burden.csv_clean
   📄 cancer_stage_diagnosis_ssa_moderate_burden.csv_clean
   📄 generate_dataset (2).py_clean
   📄 cancer_survival_afcrn_high_burden.csv_clean
   📄 cancer_survival_afcrn_low_burden.csv_clean
   📄 cancer_survival_afcrn_moderate_burden.csv_clean
   📄 dataset_infos.json_clean
   📄 datad.csv_clean
   📄 dataf1.csv_clean
   📄 medquad.csv_clean
   📄 cancer_qa_dataset_1000_clean.csv
   📄 cancer_qa_dataset_5000_clean.csv
   📄 table-components-ca43bz4f_clean.txt
   📄 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean.txt
   📄 conversation-small-1rwf4ooe_clean.txt
   📄 index-ivzj8m6u_clean.txt
   📄 root-mn12m92t_clean.txt
   📄 product-variants-ga945uk2_clean.txt
   📄 silk-hq-lutwos9z_clean.txt
   📄 code-block-editor-pane-fzo1sbww_clean.txt
   📄 bb140dcc-565b-4572-aa9e-53f02d96d04a_clean.txt
   📄 kt_clean.txt
   📄 ansi-1f6vhsjh_clean.txt
   📄 writing-block-editor-j0pgo4i4_clean.txt
   📄 code-block-m2vhenll_clean.txt
   📄 js_clean.txt
   📄 saved_resource_clean.txt
   📄 DATTASET_clean.txt
   📄 test-00000-of-00001-1fb925721582029b_clean.txt
   📄 train-00000-of-00001-c0696c2b7ee38eb5_clean.txt
   📄 test_clean.csv
   📄 conversaciones_cancer_clean.json
   📄 conversaciones_cancer (2)_clean.json
   📄 conversaciones_cancer (3)_clean.json
   📄 Regenerated_Lung_Cancer_QA_Dataset_clean.csv
   📄 train-00000-of-00001_clean.txt
   📄 bone_cancer_samples_clean.csv
   📄 brain_tumour_samples_clean.csv
   📄 breast_cancer_samples_clean.csv
   📄 colon_cancer_samples_clean.csv
   📄 gastric_cancer_samples_clean.csv
   📄 kidney_cancer_samples_clean.csv
   📄 lung_cancer_samples_clean.csv
   📄 ovarian_cancer_samples_clean.csv
   📄 prostate_cancer_samples_clean.csv
   📄 skin_cancer_samples_clean.csv
   📄 lung_cancer_clean_5K_clean.txt
   📄 train-00000-of-00004_clean.txt
   📄 train-00000-of-00001 (3)_clean.txt
   📄 train-00000-of-00001 (2)_clean.txt
   📄 cancer-risk-factors_clean.csv
   📄 cancer_clean.csv
   📄 med_clean.csv
   📄 inca-donnees-mco-10.2025_clean.txt
   📄 inca-donnees-smr-10.2025_clean.txt
   📄 inca-donnees-had-10.2025_clean.txt
   📄 synthetic_structured_clean.json
   📄 synthetic_unstructured_clean.json
   📄 train-00000-of-00001 (6)_clean.txt
   📄 generate_dataset_clean.txt
   📄 cancer_risk_factors_steps_moderate_burden_clean.csv
   📄 cancer_risk_factors_steps_low_burden_clean.csv
   📄 cancer_risk_factors_steps_high_burden_clean.csv
   📄 cancer_treatment_patterns_high_burden_clean.csv
   📄 cancer_treatment_patterns_low_burden_clean.csv
   📄 cancer_treatment_patterns_moderate_burden_clean.csv
   📄 cancer_stage_diagnosis_ssa_high_burden_clean.csv
   📄 cancer_stage_diagnosis_ssa_low_burden_clean.csv
   📄 cancer_stage_diagnosis_ssa_moderate_burden_clean.csv
   📄 generate_dataset (2)_clean.txt
   📄 cancer_survival_afcrn_high_burden_clean.csv
   📄 cancer_survival_afcrn_low_burden_clean.csv
   📄 cancer_survival_afcrn_moderate_burden_clean.csv
   📄 dataset_infos_clean.json
   📄 datad_clean.csv
   📄 dataf1_clean.csv
   📄 medquad_clean.csv
   📄 cancer_qa_dataset_1000_clean.txt
   📄 cancer_qa_dataset_5000_clean.txt
   📄 js_clean_clean.txt
   📄 dataset_clean.txt
   📄 test_clean.txt
   📄 conversaciones_cancer_clean.txt
   📄 conversaciones_cancer (2)_clean.txt
   📄 conversaciones_cancer (3)_clean.txt
   📄 Regenerated_Lung_Cancer_QA_Dataset_clean.txt
   📄 bone_cancer_samples_clean.txt
   📄 brain_tumour_samples_clean.txt
   📄 breast_cancer_samples_clean.txt
   📄 colon_cancer_samples_clean.txt
   📄 gastric_cancer_samples_clean.txt

In [ ]:
import os

folder = "/content/drive/MyDrive/datasetColab"

for root, dirs, files in os.walk(folder):
    for file in files:
        path = os.path.join(root, file)
        if os.path.getsize(path) == 0:
            os.remove(path)
            print("fichier vide supprimé :", path)

In [ ]:
import os

folder = "/content/drive/MyDrive/datasetColab"

for root, dirs, files in os.walk(folder):
    for file in files:
        if "(1)" in file:
            path = os.path.join(root, file)
            os.remove(path)
            print("doublon supprimé :", path)

In [ ]:
import os
import pandas as pd
import json
import re
import xml.etree.ElementTree as ET

root_folder = "/content/drive/MyDrive"

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^\w\s]", "", text)
    return text.strip()

for root, dirs, files in os.walk(root_folder):
    for file in files:

        path = os.path.join(root, file)
        name, ext = os.path.splitext(file)

        try:

            # CSV
            if ext == ".csv":
                df = pd.read_csv(path, encoding="latin1", on_bad_lines="skip")
                df = df.drop_duplicates()
                df = df.fillna("")
                clean_path = os.path.join(root, name + "_clean.csv")
                df.to_csv(clean_path, index=False)
                print("CSV nettoyé :", file)

            # JSON
            elif ext == ".json":
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    data = json.load(f)

                clean_path = os.path.join(root, name + "_clean.json")
                with open(clean_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=2)

                print("JSON nettoyé :", file)

            # XML
            elif ext == ".xml":
                tree = ET.parse(path)
                root_xml = tree.getroot()

                clean_path = os.path.join(root, name + "_clean.xml")
                tree.write(clean_path)

                print("XML nettoyé :", file)

            # TXT ou autres fichiers texte
            else:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()

                cleaned = clean_text(content)

                clean_path = os.path.join(root, name + "_clean.txt")
                with open(clean_path, "w", encoding="utf-8") as f:
                    f.write(cleaned)

                print("texte nettoyé :", file)

        except Exception as e:
            print("impossible traiter :", file)

texte nettoyé : Untitled0.ipynb
texte nettoyé : Copie de Bienvenue dans Colab
texte nettoyé : pfe (1).ipynb
texte nettoyé : Copie de pfe.ipynb
texte nettoyé : pfe.ipynb
texte nettoyé : Untitled0.ipynb_clean
texte nettoyé : Copie de Bienvenue dans Colab_clean
texte nettoyé : pfe (1).ipynb_clean
texte nettoyé : Copie de pfe.ipynb_clean
texte nettoyé : pfe.ipynb_clean
texte nettoyé : Untitled0_clean.txt
texte nettoyé : Copie de Bienvenue dans Colab_clean.txt
texte nettoyé : pfe (1)_clean.txt
texte nettoyé : Copie de pfe_clean.txt
texte nettoyé : pfe_clean.txt
texte nettoyé : Copie de Bienvenue dans Colab_clean_clean.txt
texte nettoyé : Untitled0_clean_clean.txt
texte nettoyé : pfe (1)_clean_clean.txt
texte nettoyé : Copie de pfe_clean_clean.txt
texte nettoyé : pfe_clean_clean.txt
texte nettoyé : Copie de Bienvenue dans Colab_clean_clean_clean.txt
texte nettoyé : Untitled0_clean_clean_clean.txt
texte nettoyé : pfe (1)_clean_clean_clean.txt
texte nettoyé : Copie de pfe_clean_clean_clean.txt
texte nettoyé : pfe_clean_clean_clean.txt
texte nettoyé : Copie de Bienvenue dans Colab_clean_clean_clean_clean.txt
texte nettoyé : Untitled0_clean_clean_clean_clean.txt
texte nettoyé : pfe (1)_clean_clean_clean_clean.txt
texte nettoyé : Copie de pfe_clean_clean_clean_clean.txt
texte nettoyé : pfe_clean_clean_clean_clean.txt
texte nettoyé : Copie de Bienvenue dans Colab_clean_clean_clean_clean_clean.txt
texte nettoyé : projets.pdf
texte nettoyé : projets.pdf_clean
texte nettoyé : projets_clean.txt
texte nettoyé : projets_clean_clean.txt
texte nettoyé : projets_clean_clean_clean.txt
texte nettoyé : projets_clean_clean_clean_clean.txt
CSV nettoyé : cancer_dataset.csv
CSV nettoyé : cancer_dataset2.csv
CSV nettoyé : final_dataset.csv
CSV nettoyé : dataset3_clean.csv
CSV nettoyé : dataset3_clean_final.csv
CSV nettoyé : cancer_dataset_clean.csv
CSV nettoyé : cancer_dataset2_clean.csv
CSV nettoyé : final_dataset_clean.csv
CSV nettoyé : dataset3_clean_clean.csv
CSV nettoyé : dataset3_clean_final_clean.csv
CSV nettoyé : cancer_dataset_clean_clean.csv
CSV nettoyé : cancer_dataset2_clean_clean.csv
CSV nettoyé : final_dataset_clean_clean.csv
CSV nettoyé : dataset3_clean_clean_clean.csv
CSV nettoyé : dataset3_clean_final_clean_clean.csv
CSV nettoyé : cancer_dataset_clean_clean_clean.csv
CSV nettoyé : cancer_dataset2_clean_clean_clean.csv
CSV nettoyé : final_dataset_clean_clean_clean.csv
CSV nettoyé : dataset3_clean_clean_clean_clean.csv
CSV nettoyé : dataset3_clean_final_clean_clean_clean.csv
CSV nettoyé : cancer_qa_dataset_1000.csv
CSV nettoyé : cancer_qa_dataset_5000.csv
texte nettoyé : silk-hq-lutwos9z.css
texte nettoyé : code-block-m2vhenll.css
texte nettoyé : kt.png
texte nettoyé : index-ivzj8m6u.css
texte nettoyé : product-variants-ga945uk2.css
texte nettoyé : code-block-editor-pane-fzo1sbww.css
texte nettoyé : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png
texte nettoyé : root-mn12m92t.css
texte nettoyé : conversation-small-1rwf4ooe.css
texte nettoyé : writing-block-editor-j0pgo4i4.css
texte nettoyé : table-components-ca43bz4f.css
texte nettoyé : ansi-1f6vhsjh.css
texte nettoyé : bb140dcc-565b-4572-aa9e-53f02d96d04a.png
texte nettoyé : js
texte nettoyé : saved_resource.html
impossible traiter : dataset.json
texte nettoyé : DATTASET.JSON
texte nettoyé : test-00000-of-00001-1fb925721582029b.parquet
texte nettoyé : train-00000-of-00001-c0696c2b7ee38eb5.parquet
CSV nettoyé : test.csv
CSV nettoyé : train.csv
JSON nettoyé : conversaciones_cancer.json
JSON nettoyé : conversaciones_cancer (2).json
JSON nettoyé : conversaciones_cancer (3).json
CSV nettoyé : Regenerated_Lung_Cancer_QA_Dataset.csv
texte nettoyé : train-00000-of-00001.parquet
CSV nettoyé : bone_cancer_samples.csv
CSV nettoyé : brain_tumour_samples.csv
CSV nettoyé : breast_cancer_samples.csv
CSV nettoyé : colon_cancer_samples.csv
CSV nettoyé : gastric_cancer_samples.csv
CSV nettoyé : kidney_cancer_samples.csv
CSV nettoyé : lung_cancer_samples.csv
CSV nettoyé : ovarian_cancer_samples.csv
CSV nettoyé : prostate_cancer_samples.csv
CSV nettoyé : skin_cancer_samples.csv
texte nettoyé : lung_cancer_clean_5K.jsonl

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

path = "/content/drive/MyDrive/datasetColab"
print(os.listdir(path))

['data_csv.cancer_files', '1_CancerGov_QA', 'archive (13)', 'cancer_dataset.csv', 'cancer_dataset2.csv', 'final_dataset.csv', 'dataset3_clean.csv', 'dataset3_clean_final.csv', 'cancer_dataset_clean.csv', 'cancer_dataset2_clean.csv', 'final_dataset_clean.csv', 'dataset3_clean_clean.csv', 'dataset3_clean_final_clean.csv', 'cancer_dataset_clean_clean.csv', 'cancer_dataset2_clean_clean.csv', 'final_dataset_clean_clean.csv', 'dataset3_clean_clean_clean.csv', 'dataset3_clean_final_clean_clean.csv', 'cancer_dataset_clean_clean_clean.csv', 'cancer_dataset2_clean_clean_clean.csv', 'final_dataset_clean_clean_clean.csv', 'dataset3_clean_clean_clean_clean.csv', 'dataset3_clean_final_clean_clean_clean.csv']

In [ ]:
import xml.etree.ElementTree as ET
import pandas as pd
import os

folder = "/content/drive/MyDrive/datasetColab/1_CancerGov_QA"

questions = []
answers = []

for file in os.listdir(folder):
    if file.endswith(".xml"):
        tree = ET.parse(os.path.join(folder, file))
        root = tree.getroot()

        for qa in root.iter('QAPair'):
            question = qa.find('Question').text
            answer = qa.find('Answer').text

            questions.append(question)
            answers.append(answer)

dataset = pd.DataFrame({
    "question": questions,
    "answer": answers
})

dataset.head()

,question,answer
0,What is (are) Ovarian Germ Cell Tumors ?,Key Points\n - Ovarian germ...
1,What are the symptoms of Ovarian Germ Cell Tum...,Signs of ovarian germ cell tumor are swelling ...
2,How to diagnose Ovarian Germ Cell Tumors ?,"Tests that examine the ovaries, pelvic area, b..."
3,What is the outlook for Ovarian Germ Cell Tumo...,Certain factors affect prognosis (chance of re...
4,What are the stages of Ovarian Germ Cell Tumors ?,Key Points\n - After ovaria...

In [ ]:
dataset.to_csv("/content/drive/MyDrive/datasetColab/cancer_dataset.csv", index=False)

In [ ]:
from sklearn.model_selection import train_test_split

train, temp = train_test_split(dataset, test_size=0.3, random_state=42)
validation, test = train_test_split(temp, test_size=0.5)

print("Train:", len(train))
print("Validation:", len(validation))
print("Test:", len(test))

Train: 4393
Validation: 942
Test: 942

In [ ]:
folder2 = "/content/drive/MyDrive/datasetColab/archive (13)"

In [ ]:
import xml.etree.ElementTree as ET
import pandas as pd
import os

folder2 = "/content/drive/MyDrive/datasetColab/archive (13)"

questions2 = []
answers2 = []

for file in os.listdir(folder2):
    if file.endswith(".xml"):
        tree = ET.parse(os.path.join(folder2, file))
        root = tree.getroot()

        for qa in root.iter('QAPair'):
            question = qa.find('Question').text
            answer = qa.find('Answer').text

            questions2.append(question)
            answers2.append(answer)

dataset2 = pd.DataFrame({
    "question": questions2,
    "answer": answers2
})

dataset2.head()

Empty DataFrame
Columns: [question, answer]
Index: []

In [ ]:
print(len(dataset2))

0

In [ ]:
dataset2.to_csv("/content/drive/MyDrive/datasetColab/cancer_dataset2.csv", index=False)

In [ ]:
dataset_final = pd.concat([dataset, dataset2], ignore_index=True)

print(len(dataset_final))

6277

In [ ]:
dataset_final.to_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv", index=False)

NameError: name 'dataset_final' is not defined

In [ ]:
folder3 = "/content/drive/MyDrive/datasetColab/data_csv.cancer_files"

In [ ]:
import os

files = os.listdir(folder3)
print(files)

['cancer_qa_dataset_1000.csv', 'cancer_qa_dataset_5000.csv', 'silk-hq-lutwos9z.css', 'code-block-m2vhenll.css', 'kt.png', 'index-ivzj8m6u.css', 'product-variants-ga945uk2.css', 'code-block-editor-pane-fzo1sbww.css', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png', 'root-mn12m92t.css', 'conversation-small-1rwf4ooe.css', 'writing-block-editor-j0pgo4i4.css', 'table-components-ca43bz4f.css', 'ansi-1f6vhsjh.css', 'bb140dcc-565b-4572-aa9e-53f02d96d04a.png', 'js', 'saved_resource.html', 'dataset.json', 'DATTASET.JSON', 'test-00000-of-00001-1fb925721582029b.parquet', 'train-00000-of-00001-c0696c2b7ee38eb5.parquet', 'test.csv', 'train.csv', 'conversaciones_cancer.json', 'conversaciones_cancer (2).json', 'conversaciones_cancer (3).json', 'Regenerated_Lung_Cancer_QA_Dataset.csv', 'train-00000-of-00001.parquet', 'bone_cancer_samples.csv', 'brain_tumour_samples.csv', 'breast_cancer_samples.csv', 'colon_cancer_samples.csv', 'gastric_cancer_samples.csv', 'kidney_cancer_samples.csv', 'lung_cancer_samples.csv', 'ovarian_cancer_samples.csv', 'prostate_cancer_samples.csv', 'skin_cancer_samples.csv', 'lung_cancer_clean_5K.jsonl', 'train-00002-of-00004.parquet', 'train-00003-of-00004.parquet', 'train-00000-of-00004.parquet', 'train-00000-of-00001 (3).parquet', 'train-00000-of-00001 (2).parquet', 'cancer-risk-factors.csv', 'cancer.csv', 'med.csv', 'inca-donnees-mco-10.2025.xlsx', 'inca-donnees-smr-10.2025.xlsx', 'inca-donnees-had-10.2025.xlsx', 'synthetic_structured.json', 'synthetic_unstructured.json', 'train-00000-of-00001 (6).parquet', 'generate_dataset.py', 'cancer_risk_factors_steps_moderate_burden.csv', 'cancer_risk_factors_steps_low_burden.csv', 'cancer_risk_factors_steps_high_burden.csv', 'cancer_treatment_patterns_high_burden.csv', 'cancer_treatment_patterns_low_burden.csv', 'cancer_treatment_patterns_moderate_burden.csv', 'cancer_stage_diagnosis_ssa_high_burden.csv', 'cancer_stage_diagnosis_ssa_low_burden.csv', 'cancer_stage_diagnosis_ssa_moderate_burden.csv', 'generate_dataset (2).py', 'cancer_survival_afcrn_high_burden.csv', 'cancer_survival_afcrn_low_burden.csv', 'cancer_survival_afcrn_moderate_burden.csv', 'dataset_infos.json', 'datad.csv', 'dataf1.csv', 'medquad.csv', 'data_csv.cancer_files', 'cancer_qa_dataset_1000.csv_clean', 'cancer_qa_dataset_5000.csv_clean', 'silk-hq-lutwos9z.css_clean', 'code-block-m2vhenll.css_clean', 'kt.png_clean', 'index-ivzj8m6u.css_clean', 'product-variants-ga945uk2.css_clean', 'code-block-editor-pane-fzo1sbww.css_clean', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png_clean', 'root-mn12m92t.css_clean', 'conversation-small-1rwf4ooe.css_clean', 'writing-block-editor-j0pgo4i4.css_clean', 'table-components-ca43bz4f.css_clean', 'ansi-1f6vhsjh.css_clean', 'bb140dcc-565b-4572-aa9e-53f02d96d04a.png_clean', 'js_clean', 'saved_resource.html_clean', 'dataset.json_clean', 'DATTASET.JSON_clean', 'test-00000-of-00001-1fb925721582029b.parquet_clean', 'train-00000-of-00001-c0696c2b7ee38eb5.parquet_clean', 'test.csv_clean', 'train.csv_clean', 'conversaciones_cancer.json_clean', 'conversaciones_cancer (2).json_clean', 'conversaciones_cancer (3).json_clean', 'Regenerated_Lung_Cancer_QA_Dataset.csv_clean', 'train-00000-of-00001.parquet_clean', 'bone_cancer_samples.csv_clean', 'brain_tumour_samples.csv_clean', 'breast_cancer_samples.csv_clean', 'colon_cancer_samples.csv_clean', 'gastric_cancer_samples.csv_clean', 'kidney_cancer_samples.csv_clean', 'lung_cancer_samples.csv_clean', 'ovarian_cancer_samples.csv_clean', 'prostate_cancer_samples.csv_clean', 'skin_cancer_samples.csv_clean', 'lung_cancer_clean_5K.jsonl_clean', 'train-00002-of-00004.parquet_clean', 'train-00003-of-00004.parquet_clean', 'train-00000-of-00001 (3).parquet_clean', 'train-00000-of-00001 (2).parquet_clean', 'cancer-risk-factors.csv_clean', 'cancer.csv_clean', 'med.csv_clean', 'inca-donnees-mco-10.2025.xlsx_clean', 'inca-donnees-smr-10.2025.xlsx_clean', 'inca-donnees-had-10.2025.xlsx_clean', 'synthetic_structured.json_clean', 'synthetic_unstructured.json_clean', 'train-00000-of-00001 (6).parquet_clean', 'generate_dataset.py_clean', 'cancer_risk_factors_steps_moderate_burden.csv_clean', 'cancer_risk_factors_steps_low_burden.csv_clean', 'cancer_risk_factors_steps_high_burden.csv_clean', 'cancer_treatment_patterns_high_burden.csv_clean', 'cancer_treatment_patterns_low_burden.csv_clean', 'cancer_treatment_patterns_moderate_burden.csv_clean', 'cancer_stage_diagnosis_ssa_high_burden.csv_clean', 'cancer_stage_diagnosis_ssa_low_burden.csv_clean', 'cancer_stage_diagnosis_ssa_moderate_burden.csv_clean', 'generate_dataset (2).py_clean', 'cancer_survival_afcrn_high_burden.csv_clean', 'cancer_survival_afcrn_low_burden.csv_clean', 'cancer_survival_afcrn_moderate_burden.csv_clean', 'dataset_infos.json_clean', 'datad.csv_clean', 'dataf1.csv_clean', 'medquad.csv_clean', 'cancer_qa_dataset_1000_clean.csv', 'cancer_qa_dataset_5000_clean.csv', 'silk-hq-lutwos9z_clean.txt', 'code-block-m2vhenll_clean.txt', 'kt_clean.txt', 'index-ivzj8m6u_clean.txt', 'product-variants-ga945uk2_clean.txt', 'code-block-editor-pane-fzo1sbww_clean.txt', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean.txt', 'root-mn12m92t_clean.txt', 'conversation-small-1rwf4ooe_clean.txt', 'writing-block-editor-j0pgo4i4_clean.txt', 'table-components-ca43bz4f_clean.txt', 'ansi-1f6vhsjh_clean.txt', 'bb140dcc-565b-4572-aa9e-53f02d96d04a_clean.txt', 'js_clean.txt', 'saved_resource_clean.txt', 'DATTASET_clean.txt', 'test-00000-of-00001-1fb925721582029b_clean.txt', 'train-00000-of-00001-c0696c2b7ee38eb5_clean.txt', 'test_clean.csv', 'train_clean.csv', 'conversaciones_cancer_clean.json', 'conversaciones_cancer (2)_clean.json', 'conversaciones_cancer (3)_clean.json', 'Regenerated_Lung_Cancer_QA_Dataset_clean.csv', 'train-00000-of-00001_clean.txt', 'bone_cancer_samples_clean.csv', 'brain_tumour_samples_clean.csv', 'breast_cancer_samples_clean.csv', 'colon_cancer_samples_clean.csv', 'gastric_cancer_samples_clean.csv', 'kidney_cancer_samples_clean.csv', 'lung_cancer_samples_clean.csv', 'ovarian_cancer_samples_clean.csv', 'prostate_cancer_samples_clean.csv', 'skin_cancer_samples_clean.csv', 'lung_cancer_clean_5K_clean.txt', 'train-00002-of-00004_clean.txt', 'train-00003-of-00004_clean.txt', 'train-00000-of-00004_clean.txt', 'train-00000-of-00001 (3)_clean.txt', 'train-00000-of-00001 (2)_clean.txt', 'cancer-risk-factors_clean.csv', 'cancer_clean.csv', 'med_clean.csv', 'inca-donnees-mco-10.2025_clean.txt', 'inca-donnees-smr-10.2025_clean.txt', 'inca-donnees-had-10.2025_clean.txt', 'synthetic_structured_clean.json', 'synthetic_unstructured_clean.json', 'train-00000-of-00001 (6)_clean.txt', 'generate_dataset_clean.txt', 'cancer_risk_factors_steps_moderate_burden_clean.csv', 'cancer_risk_factors_steps_low_burden_clean.csv', 'cancer_risk_factors_steps_high_burden_clean.csv', 'cancer_treatment_patterns_high_burden_clean.csv', 'cancer_treatment_patterns_low_burden_clean.csv', 'cancer_treatment_patterns_moderate_burden_clean.csv', 'cancer_stage_diagnosis_ssa_high_burden_clean.csv', 'cancer_stage_diagnosis_ssa_low_burden_clean.csv', 'cancer_stage_diagnosis_ssa_moderate_burden_clean.csv', 'generate_dataset (2)_clean.txt', 'cancer_survival_afcrn_high_burden_clean.csv', 'cancer_survival_afcrn_low_burden_clean.csv', 'cancer_survival_afcrn_moderate_burden_clean.csv', 'dataset_infos_clean.json', 'datad_clean.csv', 'dataf1_clean.csv', 'medquad_clean.csv', 'cancer_qa_dataset_1000_clean.txt', 'cancer_qa_dataset_5000_clean.txt', 'js_clean_clean.txt', 'dataset_clean.txt', 'test_clean.txt', 'train_clean.txt', 'conversaciones_cancer_clean.txt', 'conversaciones_cancer (2)_clean.txt', 'conversaciones_cancer (3)_clean.txt', 'Regenerated_Lung_Cancer_QA_Dataset_clean.txt', 'bone_cancer_samples_clean.txt', 'brain_tumour_samples_clean.txt', 'breast_cancer_samples_clean.txt', 'colon_cancer_samples_clean.txt', 'gastric_cancer_samples_clean.txt', 'kidney_cancer_samples_clean.txt', 'lung_cancer_samples_clean.txt', 'ovarian_cancer_samples_clean.txt', 'prostate_cancer_samples_clean.txt', 'skin_cancer_samples_clean.txt', 'cancer-risk-factors_clean.txt', 'cancer_clean.txt', 'med_clean.txt', 'synthetic_structured_clean.txt', 'synthetic_unstructured_clean.txt', 'cancer_risk_factors_steps_moderate_burden_clean.txt', 'cancer_risk_factors_steps_low_burden_clean.txt', 'cancer_risk_factors_steps_high_burden_clean.txt', 'cancer_treatment_patterns_high_burden_clean.txt', 'cancer_treatment_patterns_low_burden_clean.txt', 'cancer_treatment_patterns_moderate_burden_clean.txt', 'cancer_stage_diagnosis_ssa_high_burden_clean.txt', 'cancer_stage_diagnosis_ssa_low_burden_clean.txt', 'cancer_stage_diagnosis_ssa_moderate_burden_clean.txt', 'cancer_survival_afcrn_high_burden_clean.txt', 'cancer_survival_afcrn_low_burden_clean.txt', 'cancer_survival_afcrn_moderate_burden_clean.txt', 'dataset_infos_clean.txt', 'datad_clean.txt', 'dataf1_clean.txt', 'medquad_clean.txt', 'cancer_qa_dataset_1000_clean_clean.csv', 'cancer_qa_dataset_5000_clean_clean.csv', 'silk-hq-lutwos9z_clean_clean.txt', 'code-block-m2vhenll_clean_clean.txt', 'kt_clean_clean.txt', 'index-ivzj8m6u_clean_clean.txt', 'product-variants-ga945uk2_clean_clean.txt', 'code-block-editor-pane-fzo1sbww_clean_clean.txt', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean_clean.txt', 'root-mn12m92t_clean_clean.txt', 'conversation-small-1rwf4ooe_clean_clean.txt', 'writing-block-editor-j0pgo4i4_clean_clean.txt', 'table-components-ca43bz4f_clean_clean.txt', 'ansi-1f6vhsjh_clean_clean.txt', 'bb140dcc-565b-4572-aa9e-53f02d96d04a_clean_clean.txt', 'saved_resource_clean_clean.txt', 'DATTASET_clean_clean.txt', 'test-00000-of-00001-1fb925721582029b_clean_clean.txt', 'train-00000-of-00001-c0696c2b7ee38eb5_clean_clean.txt', 'test_clean_clean.csv', 'train_clean_clean.csv', 'conversaciones_cancer_clean_clean.json', 'conversaciones_cancer (2)_clean_clean.json', 'conversaciones_cancer (3)_clean_clean.json', 'Regenerated_Lung_Cancer_QA_Dataset_clean_clean.csv', 'train-00000-of-00001_clean_clean.txt', 'bone_cancer_samples_clean_clean.csv', 'brain_tumour_samples_clean_clean.csv', 'breast_cancer_samples_clean_clean.csv', 'colon_cancer_samples_clean_clean.csv', 'gastric_cancer_samples_clean_clean.csv', 'kidney_cancer_samples_clean_clean.csv', 'lung_cancer_samples_clean_clean.csv', 'ovarian_cancer_samples_clean_clean.csv', 'prostate_cancer_samples_clean_clean.csv', 'skin_cancer_samples_clean_clean.csv', 'lung_cancer_clean_5K_clean_clean.txt']

In [ ]:
import os

files = os.listdir(folder3)
print("Nombre de fichiers :", len(files))
print(files[:10])

Nombre de fichiers : 290
['cancer_qa_dataset_1000.csv', 'cancer_qa_dataset_5000.csv', 'silk-hq-lutwos9z.css', 'code-block-m2vhenll.css', 'kt.png', 'index-ivzj8m6u.css', 'product-variants-ga945uk2.css', 'code-block-editor-pane-fzo1sbww.css', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png', 'root-mn12m92t.css']

In [ ]:
import pandas as pd
import json
import xml.etree.ElementTree as ET

dataframes = []

for file in files:

    path = os.path.join(folder3, file)

    try:
        # essayer CSV
        df = pd.read_csv(path)
        dataframes.append(df)
        print("CSV lu :", file)
        continue
    except:
        pass

    try:
        # essayer JSON
        with open(path) as f:
            data = json.load(f)
            df = pd.DataFrame(data)
            dataframes.append(df)
            print("JSON lu :", file)
            continue
    except:
        pass

    try:
        # essayer XML
        tree = ET.parse(path)
        root = tree.getroot()

        questions = []
        answers = []

        for qa in root.iter("QAPair"):
            q = qa.find("Question").text
            a = qa.find("Answer").text

            questions.append(q)
            answers.append(a)

        df = pd.DataFrame({
            "question": questions,
            "answer": answers
        })

        dataframes.append(df)
        print("XML lu :", file)
        continue
    except:
        pass

    try:
        # essayer texte simple
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.readlines()

        df = pd.DataFrame({"text": lines})
        dataframes.append(df)

        print("TXT lu :", file)
    except:
        print("Impossible de lire :", file)

CSV lu : cancer_qa_dataset_1000.csv
CSV lu : cancer_qa_dataset_5000.csv
CSV lu : silk-hq-lutwos9z.css
CSV lu : code-block-m2vhenll.css
TXT lu : kt.png
CSV lu : index-ivzj8m6u.css
CSV lu : product-variants-ga945uk2.css
CSV lu : code-block-editor-pane-fzo1sbww.css
TXT lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png
CSV lu : root-mn12m92t.css
CSV lu : conversation-small-1rwf4ooe.css
CSV lu : writing-block-editor-j0pgo4i4.css
CSV lu : table-components-ca43bz4f.css
CSV lu : ansi-1f6vhsjh.css
TXT lu : bb140dcc-565b-4572-aa9e-53f02d96d04a.png
TXT lu : js
CSV lu : saved_resource.html
TXT lu : dataset.json
TXT lu : DATTASET.JSON
TXT lu : test-00000-of-00001-1fb925721582029b.parquet
TXT lu : train-00000-of-00001-c0696c2b7ee38eb5.parquet
CSV lu : test.csv
CSV lu : train.csv
JSON lu : conversaciones_cancer.json
JSON lu : conversaciones_cancer (2).json
JSON lu : conversaciones_cancer (3).json
CSV lu : Regenerated_Lung_Cancer_QA_Dataset.csv
TXT lu : train-00000-of-00001.parquet
CSV lu : bone_cancer_samples.csv
CSV lu : brain_tumour_samples.csv
CSV lu : breast_cancer_samples.csv
CSV lu : colon_cancer_samples.csv
CSV lu : gastric_cancer_samples.csv
CSV lu : kidney_cancer_samples.csv
CSV lu : lung_cancer_samples.csv
CSV lu : ovarian_cancer_samples.csv
CSV lu : prostate_cancer_samples.csv
CSV lu : skin_cancer_samples.csv
TXT lu : lung_cancer_clean_5K.jsonl
TXT lu : train-00002-of-00004.parquet
TXT lu : train-00003-of-00004.parquet
TXT lu : train-00000-of-00004.parquet
TXT lu : train-00000-of-00001 (3).parquet
TXT lu : train-00000-of-00001 (2).parquet
CSV lu : cancer-risk-factors.csv
CSV lu : cancer.csv
TXT lu : med.csv
TXT lu : inca-donnees-mco-10.2025.xlsx
TXT lu : inca-donnees-smr-10.2025.xlsx
TXT lu : inca-donnees-had-10.2025.xlsx
JSON lu : synthetic_structured.json
JSON lu : synthetic_unstructured.json
TXT lu : train-00000-of-00001 (6).parquet
TXT lu : generate_dataset.py
CSV lu : cancer_risk_factors_steps_moderate_burden.csv
CSV lu : cancer_risk_factors_steps_low_burden.csv
CSV lu : cancer_risk_factors_steps_high_burden.csv
CSV lu : cancer_treatment_patterns_high_burden.csv
CSV lu : cancer_treatment_patterns_low_burden.csv
CSV lu : cancer_treatment_patterns_moderate_burden.csv
CSV lu : cancer_stage_diagnosis_ssa_high_burden.csv
CSV lu : cancer_stage_diagnosis_ssa_low_burden.csv
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden.csv
TXT lu : generate_dataset (2).py
CSV lu : cancer_survival_afcrn_high_burden.csv
CSV lu : cancer_survival_afcrn_low_burden.csv
CSV lu : cancer_survival_afcrn_moderate_burden.csv
JSON lu : dataset_infos.json
CSV lu : datad.csv
TXT lu : dataf1.csv
CSV lu : medquad.csv
Impossible de lire : data_csv.cancer_files
CSV lu : cancer_qa_dataset_1000.csv_clean
CSV lu : cancer_qa_dataset_5000.csv_clean
CSV lu : silk-hq-lutwos9z.css_clean
CSV lu : code-block-m2vhenll.css_clean
CSV lu : kt.png_clean
CSV lu : index-ivzj8m6u.css_clean
CSV lu : product-variants-ga945uk2.css_clean
CSV lu : code-block-editor-pane-fzo1sbww.css_clean
CSV lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png_clean
CSV lu : root-mn12m92t.css_clean
CSV lu : conversation-small-1rwf4ooe.css_clean
CSV lu : writing-block-editor-j0pgo4i4.css_clean
CSV lu : table-components-ca43bz4f.css_clean
CSV lu : ansi-1f6vhsjh.css_clean
CSV lu : bb140dcc-565b-4572-aa9e-53f02d96d04a.png_clean
CSV lu : js_clean
CSV lu : saved_resource.html_clean
CSV lu : dataset.json_clean
CSV lu : DATTASET.JSON_clean
CSV lu : test-00000-of-00001-1fb925721582029b.parquet_clean
CSV lu : train-00000-of-00001-c0696c2b7ee38eb5.parquet_clean
CSV lu : test.csv_clean
CSV lu : train.csv_clean
CSV lu : conversaciones_cancer.json_clean
CSV lu : conversaciones_cancer (2).json_clean
CSV lu : conversaciones_cancer (3).json_clean
CSV lu : Regenerated_Lung_Cancer_QA_Dataset.csv_clean
CSV lu : train-00000-of-00001.parquet_clean
CSV lu : bone_cancer_samples.csv_clean
CSV lu : brain_tumour_samples.csv_clean
CSV lu : breast_cancer_samples.csv_clean
CSV lu : colon_cancer_samples.csv_clean
CSV lu : gastric_cancer_samples.csv_clean
CSV lu : kidney_cancer_samples.csv_clean
CSV lu : lung_cancer_samples.csv_clean
CSV lu : ovarian_cancer_samples.csv_clean
CSV lu : prostate_cancer_samples.csv_clean
CSV lu : skin_cancer_samples.csv_clean
CSV lu : lung_cancer_clean_5K.jsonl_clean
CSV lu : train-00002-of-00004.parquet_clean
CSV lu : train-00003-of-00004.parquet_clean
CSV lu : train-00000-of-00001 (3).parquet_clean
CSV lu : train-00000-of-00001 (2).parquet_clean
CSV lu : cancer-risk-factors.csv_clean
CSV lu : cancer.csv_clean
CSV lu : med.csv_clean
CSV lu : inca-donnees-mco-10.2025.xlsx_clean
CSV lu : inca-donnees-smr-10.2025.xlsx_clean
CSV lu : inca-donnees-had-10.2025.xlsx_clean
CSV lu : synthetic_structured.json_clean
CSV lu : synthetic_unstructured.json_clean
CSV lu : train-00000-of-00001 (6).parquet_clean
CSV lu : generate_dataset.py_clean
CSV lu : cancer_risk_factors_steps_moderate_burden.csv_clean
CSV lu : cancer_risk_factors_steps_low_burden.csv_clean
CSV lu : cancer_risk_factors_steps_high_burden.csv_clean
CSV lu : cancer_treatment_patterns_high_burden.csv_clean
CSV lu : cancer_treatment_patterns_low_burden.csv_clean
CSV lu : cancer_treatment_patterns_moderate_burden.csv_clean
CSV lu : cancer_stage_diagnosis_ssa_high_burden.csv_clean
CSV lu : cancer_stage_diagnosis_ssa_low_burden.csv_clean
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden.csv_clean
CSV lu : generate_dataset (2).py_clean
CSV lu : cancer_survival_afcrn_high_burden.csv_clean
CSV lu : cancer_survival_afcrn_low_burden.csv_clean
CSV lu : cancer_survival_afcrn_moderate_burden.csv_clean
CSV lu : dataset_infos.json_clean
CSV lu : datad.csv_clean
CSV lu : dataf1.csv_clean
CSV lu : medquad.csv_clean
CSV lu : cancer_qa_dataset_1000_clean.csv
CSV lu : cancer_qa_dataset_5000_clean.csv
CSV lu : silk-hq-lutwos9z_clean.txt
CSV lu : code-block-m2vhenll_clean.txt
CSV lu : kt_clean.txt
CSV lu : index-ivzj8m6u_clean.txt
CSV lu : product-variants-ga945uk2_clean.txt
CSV lu : code-block-editor-pane-fzo1sbww_clean.txt
CSV lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean.txt
CSV lu : root-mn12m92t_clean.txt
CSV lu : conversation-small-1rwf4ooe_clean.txt
CSV lu : writing-block-editor-j0pgo4i4_clean.txt
CSV lu : table-components-ca43bz4f_clean.txt
CSV lu : ansi-1f6vhsjh_clean.txt
CSV lu : bb140dcc-565b-4572-aa9e-53f02d96d04a_clean.txt
CSV lu : js_clean.txt
CSV lu : saved_resource_clean.txt
CSV lu : DATTASET_clean.txt
CSV lu : test-00000-of-00001-1fb925721582029b_clean.txt
CSV lu : train-00000-of-00001-c0696c2b7ee38eb5_clean.txt
CSV lu : test_clean.csv
CSV lu : train_clean.csv
JSON lu : conversaciones_cancer_clean.json
JSON lu : conversaciones_cancer (2)_clean.json
JSON lu : conversaciones_cancer (3)_clean.json
CSV lu : Regenerated_Lung_Cancer_QA_Dataset_clean.csv
CSV lu : train-00000-of-00001_clean.txt
CSV lu : bone_cancer_samples_clean.csv
CSV lu : brain_tumour_samples_clean.csv
CSV lu : breast_cancer_samples_clean.csv
CSV lu : colon_cancer_samples_clean.csv
CSV lu : gastric_cancer_samples_clean.csv
CSV lu : kidney_cancer_samples_clean.csv
CSV lu : lung_cancer_samples_clean.csv
CSV lu : ovarian_cancer_samples_clean.csv
CSV lu : prostate_cancer_samples_clean.csv
CSV lu : skin_cancer_samples_clean.csv
CSV lu : lung_cancer_clean_5K_clean.txt
CSV lu : train-00002-of-00004_clean.txt
CSV lu : train-00003-of-00004_clean.txt
CSV lu : train-00000-of-00004_clean.txt
CSV lu : train-00000-of-00001 (3)_clean.txt
CSV lu : train-00000-of-00001 (2)_clean.txt
CSV lu : cancer-risk-factors_clean.csv
CSV lu : cancer_clean.csv
CSV lu : med_clean.csv
CSV lu : inca-donnees-mco-10.2025_clean.txt
CSV lu : inca-donnees-smr-10.2025_clean.txt
CSV lu : inca-donnees-had-10.2025_clean.txt
JSON lu : synthetic_structured_clean.json
JSON lu : synthetic_unstructured_clean.json
CSV lu : train-00000-of-00001 (6)_clean.txt
CSV lu : generate_dataset_clean.txt
CSV lu : cancer_risk_factors_steps_moderate_burden_clean.csv
CSV lu : cancer_risk_factors_steps_low_burden_clean.csv
CSV lu : cancer_risk_factors_steps_high_burden_clean.csv
CSV lu : cancer_treatment_patterns_high_burden_clean.csv
CSV lu : cancer_treatment_patterns_low_burden_clean.csv
CSV lu : cancer_treatment_patterns_moderate_burden_clean.csv
CSV lu : cancer_stage_diagnosis_ssa_high_burden_clean.csv
CSV lu : cancer_stage_diagnosis_ssa_low_burden_clean.csv
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden_clean.csv
CSV lu : generate_dataset (2)_clean.txt
CSV lu : cancer_survival_afcrn_high_burden_clean.csv
CSV lu : cancer_survival_afcrn_low_burden_clean.csv
CSV lu : cancer_survival_afcrn_moderate_burden_clean.csv
JSON lu : dataset_infos_clean.json
CSV lu : datad_clean.csv
CSV lu : dataf1_clean.csv
CSV lu : medquad_clean.csv
CSV lu : cancer_qa_dataset_1000_clean.txt
CSV lu : cancer_qa_dataset_5000_clean.txt
CSV lu : js_clean_clean.txt
CSV lu : dataset_clean.txt
CSV lu : test_clean.txt
CSV lu : train_clean.txt
CSV lu : conversaciones_cancer_clean.txt
CSV lu : conversaciones_cancer (2)_clean.txt
CSV lu : conversaciones_cancer (3)_clean.txt
CSV lu : Regenerated_Lung_Cancer_QA_Dataset_clean.txt
CSV lu : bone_cancer_samples_clean.txt
CSV lu : brain_tumour_samples_clean.txt
CSV lu : breast_cancer_samples_clean.txt
CSV lu : colon_cancer_samples_clean.txt
CSV lu : gastric_cancer_samples_clean.txt
CSV lu : kidney_cancer_samples_clean.txt
CSV lu : lung_cancer_samples_clean.txt
CSV lu : ovarian_cancer_samples_clean.txt
CSV lu : prostate_cancer_samples_clean.txt
CSV lu : skin_cancer_samples_clean.txt
CSV lu : cancer-risk-factors_clean.txt
CSV lu : cancer_clean.txt
CSV lu : med_clean.txt
CSV lu : synthetic_structured_clean.txt
CSV lu : synthetic_unstructured_clean.txt
CSV lu : cancer_risk_factors_steps_moderate_burden_clean.txt
CSV lu : cancer_risk_factors_steps_low_burden_clean.txt
CSV lu : cancer_risk_factors_steps_high_burden_clean.txt
CSV lu : cancer_treatment_patterns_high_burden_clean.txt
CSV lu : cancer_treatment_patterns_low_burden_clean.txt
CSV lu : cancer_treatment_patterns_moderate_burden_clean.txt
CSV lu : cancer_stage_diagnosis_ssa_high_burden_clean.txt
CSV lu : cancer_stage_diagnosis_ssa_low_burden_clean.txt
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden_clean.txt
CSV lu : cancer_survival_afcrn_high_burden_clean.txt
CSV lu : cancer_survival_afcrn_low_burden_clean.txt
CSV lu : cancer_survival_afcrn_moderate_burden_clean.txt
CSV lu : dataset_infos_clean.txt
CSV lu : datad_clean.txt
CSV lu : dataf1_clean.txt
CSV lu : medquad_clean.txt
CSV lu : cancer_qa_dataset_1000_clean_clean.csv
CSV lu : cancer_qa_dataset_5000_clean_clean.csv
CSV lu : silk-hq-lutwos9z_clean_clean.txt
CSV lu : code-block-m2vhenll_clean_clean.txt
CSV lu : kt_clean_clean.txt
CSV lu : index-ivzj8m6u_clean_clean.txt
CSV lu : product-variants-ga945uk2_clean_clean.txt
CSV lu : code-block-editor-pane-fzo1sbww_clean_clean.txt
CSV lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean_clean.txt
CSV lu : root-mn12m92t_clean_clean.txt
CSV lu : conversation-small-1rwf4ooe_clean_clean.txt
CSV lu : writing-block-editor-j0pgo4i4_clean_clean.txt
CSV lu : table-components-ca43bz4f_clean_clean.txt
CSV lu : ansi-1f6vhsjh_clean_clean.txt
CSV lu : bb140dcc-565b-4572-aa9e-53f02d96d04a_clean_clean.txt
CSV lu : saved_resource_clean_clean.txt
CSV lu : DATTASET_clean_clean.txt
CSV lu : test-00000-of-00001-1fb925721582029b_clean_clean.txt
CSV lu : train-00000-of-00001-c0696c2b7ee38eb5_clean_clean.txt
CSV lu : test_clean_clean.csv
CSV lu : train_clean_clean.csv
JSON lu : conversaciones_cancer_clean_clean.json
JSON lu : conversaciones_cancer (2)_clean_clean.json
JSON lu : conversaciones_cancer (3)_clean_clean.json
CSV lu : Regenerated_Lung_Cancer_QA_Dataset_clean_clean.csv
CSV lu : train-00000-of-00001_clean_clean.txt
CSV lu : bone_cancer_samples_clean_clean.csv
CSV lu : brain_tumour_samples_clean_clean.csv
CSV lu : breast_cancer_samples_clean_clean.csv
CSV lu : colon_cancer_samples_clean_clean.csv
CSV lu : gastric_cancer_samples_clean_clean.csv
CSV lu : kidney_cancer_samples_clean_clean.csv
CSV lu : lung_cancer_samples_clean_clean.csv
CSV lu : ovarian_cancer_samples_clean_clean.csv
CSV lu : prostate_cancer_samples_clean_clean.csv
CSV lu : skin_cancer_samples_clean_clean.csv
CSV lu : lung_cancer_clean_5K_clean_clean.txt

In [ ]:
import os
import pandas as pd
import json
import xml.etree.ElementTree as ET

In [ ]:
folder3 = "/content/drive/MyDrive/datasetColab/data_csv.cancer_files"

In [ ]:
files = os.listdir(folder3)

print("Nombre de fichiers :", len(files))
print(files[:10])

Nombre de fichiers : 290
['cancer_qa_dataset_1000.csv', 'cancer_qa_dataset_5000.csv', 'silk-hq-lutwos9z.css', 'code-block-m2vhenll.css', 'kt.png', 'index-ivzj8m6u.css', 'product-variants-ga945uk2.css', 'code-block-editor-pane-fzo1sbww.css', '1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png', 'root-mn12m92t.css']

In [ ]:
dataframes = []

for file in files:

    path = os.path.join(folder3, file)

    # CSV
    try:
        df = pd.read_csv(path)
        dataframes.append(df)
        print("CSV lu :", file)
        continue
    except:
        pass

    # JSON
    try:
        with open(path) as f:
            data = json.load(f)
            df = pd.DataFrame(data)
            dataframes.append(df)
            print("JSON lu :", file)
            continue
    except:
        pass

    # XML
    try:
        tree = ET.parse(path)
        root = tree.getroot()

        questions = []
        answers = []

        for qa in root.iter("QAPair"):
            q = qa.find("Question").text
            a = qa.find("Answer").text

            questions.append(q)
            answers.append(a)

        df = pd.DataFrame({
            "question": questions,
            "answer": answers
        })

        dataframes.append(df)
        print("XML lu :", file)
        continue
    except:
        pass

    # TEXTE
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.readlines()

        df = pd.DataFrame({"text": lines})
        dataframes.append(df)

        print("TXT lu :", file)

    except:
        print("Impossible de lire :", file)

CSV lu : cancer_qa_dataset_1000.csv
CSV lu : cancer_qa_dataset_5000.csv
CSV lu : silk-hq-lutwos9z.css
CSV lu : code-block-m2vhenll.css
TXT lu : kt.png
CSV lu : index-ivzj8m6u.css
CSV lu : product-variants-ga945uk2.css
CSV lu : code-block-editor-pane-fzo1sbww.css
TXT lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png
CSV lu : root-mn12m92t.css
CSV lu : conversation-small-1rwf4ooe.css
CSV lu : writing-block-editor-j0pgo4i4.css
CSV lu : table-components-ca43bz4f.css
CSV lu : ansi-1f6vhsjh.css
TXT lu : bb140dcc-565b-4572-aa9e-53f02d96d04a.png
TXT lu : js
CSV lu : saved_resource.html
TXT lu : dataset.json
TXT lu : DATTASET.JSON
TXT lu : test-00000-of-00001-1fb925721582029b.parquet
TXT lu : train-00000-of-00001-c0696c2b7ee38eb5.parquet
CSV lu : test.csv
CSV lu : train.csv
JSON lu : conversaciones_cancer.json
JSON lu : conversaciones_cancer (2).json
JSON lu : conversaciones_cancer (3).json
CSV lu : Regenerated_Lung_Cancer_QA_Dataset.csv
TXT lu : train-00000-of-00001.parquet
CSV lu : bone_cancer_samples.csv
CSV lu : brain_tumour_samples.csv
CSV lu : breast_cancer_samples.csv
CSV lu : colon_cancer_samples.csv
CSV lu : gastric_cancer_samples.csv
CSV lu : kidney_cancer_samples.csv
CSV lu : lung_cancer_samples.csv
CSV lu : ovarian_cancer_samples.csv
CSV lu : prostate_cancer_samples.csv
CSV lu : skin_cancer_samples.csv
TXT lu : lung_cancer_clean_5K.jsonl
TXT lu : train-00002-of-00004.parquet
TXT lu : train-00003-of-00004.parquet
TXT lu : train-00000-of-00004.parquet
TXT lu : train-00000-of-00001 (3).parquet
TXT lu : train-00000-of-00001 (2).parquet
CSV lu : cancer-risk-factors.csv
CSV lu : cancer.csv
TXT lu : med.csv
TXT lu : inca-donnees-mco-10.2025.xlsx
TXT lu : inca-donnees-smr-10.2025.xlsx
TXT lu : inca-donnees-had-10.2025.xlsx
JSON lu : synthetic_structured.json
JSON lu : synthetic_unstructured.json
TXT lu : train-00000-of-00001 (6).parquet
TXT lu : generate_dataset.py
CSV lu : cancer_risk_factors_steps_moderate_burden.csv
CSV lu : cancer_risk_factors_steps_low_burden.csv
CSV lu : cancer_risk_factors_steps_high_burden.csv
CSV lu : cancer_treatment_patterns_high_burden.csv
CSV lu : cancer_treatment_patterns_low_burden.csv
CSV lu : cancer_treatment_patterns_moderate_burden.csv
CSV lu : cancer_stage_diagnosis_ssa_high_burden.csv
CSV lu : cancer_stage_diagnosis_ssa_low_burden.csv
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden.csv
TXT lu : generate_dataset (2).py
CSV lu : cancer_survival_afcrn_high_burden.csv
CSV lu : cancer_survival_afcrn_low_burden.csv
CSV lu : cancer_survival_afcrn_moderate_burden.csv
JSON lu : dataset_infos.json
CSV lu : datad.csv
TXT lu : dataf1.csv
CSV lu : medquad.csv
Impossible de lire : data_csv.cancer_files
CSV lu : cancer_qa_dataset_1000.csv_clean
CSV lu : cancer_qa_dataset_5000.csv_clean
CSV lu : silk-hq-lutwos9z.css_clean
CSV lu : code-block-m2vhenll.css_clean
CSV lu : kt.png_clean
CSV lu : index-ivzj8m6u.css_clean
CSV lu : product-variants-ga945uk2.css_clean
CSV lu : code-block-editor-pane-fzo1sbww.css_clean
CSV lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90.png_clean
CSV lu : root-mn12m92t.css_clean
CSV lu : conversation-small-1rwf4ooe.css_clean
CSV lu : writing-block-editor-j0pgo4i4.css_clean
CSV lu : table-components-ca43bz4f.css_clean
CSV lu : ansi-1f6vhsjh.css_clean
CSV lu : bb140dcc-565b-4572-aa9e-53f02d96d04a.png_clean
CSV lu : js_clean
CSV lu : saved_resource.html_clean
CSV lu : dataset.json_clean
CSV lu : DATTASET.JSON_clean
CSV lu : test-00000-of-00001-1fb925721582029b.parquet_clean
CSV lu : train-00000-of-00001-c0696c2b7ee38eb5.parquet_clean
CSV lu : test.csv_clean
CSV lu : train.csv_clean
CSV lu : conversaciones_cancer.json_clean
CSV lu : conversaciones_cancer (2).json_clean
CSV lu : conversaciones_cancer (3).json_clean
CSV lu : Regenerated_Lung_Cancer_QA_Dataset.csv_clean
CSV lu : train-00000-of-00001.parquet_clean
CSV lu : bone_cancer_samples.csv_clean
CSV lu : brain_tumour_samples.csv_clean
CSV lu : breast_cancer_samples.csv_clean
CSV lu : colon_cancer_samples.csv_clean
CSV lu : gastric_cancer_samples.csv_clean
CSV lu : kidney_cancer_samples.csv_clean
CSV lu : lung_cancer_samples.csv_clean
CSV lu : ovarian_cancer_samples.csv_clean
CSV lu : prostate_cancer_samples.csv_clean
CSV lu : skin_cancer_samples.csv_clean
CSV lu : lung_cancer_clean_5K.jsonl_clean
CSV lu : train-00002-of-00004.parquet_clean
CSV lu : train-00003-of-00004.parquet_clean
CSV lu : train-00000-of-00001 (3).parquet_clean
CSV lu : train-00000-of-00001 (2).parquet_clean
CSV lu : cancer-risk-factors.csv_clean
CSV lu : cancer.csv_clean
CSV lu : med.csv_clean
CSV lu : inca-donnees-mco-10.2025.xlsx_clean
CSV lu : inca-donnees-smr-10.2025.xlsx_clean
CSV lu : inca-donnees-had-10.2025.xlsx_clean
CSV lu : synthetic_structured.json_clean
CSV lu : synthetic_unstructured.json_clean
CSV lu : train-00000-of-00001 (6).parquet_clean
CSV lu : generate_dataset.py_clean
CSV lu : cancer_risk_factors_steps_moderate_burden.csv_clean
CSV lu : cancer_risk_factors_steps_low_burden.csv_clean
CSV lu : cancer_risk_factors_steps_high_burden.csv_clean
CSV lu : cancer_treatment_patterns_high_burden.csv_clean
CSV lu : cancer_treatment_patterns_low_burden.csv_clean
CSV lu : cancer_treatment_patterns_moderate_burden.csv_clean
CSV lu : cancer_stage_diagnosis_ssa_high_burden.csv_clean
CSV lu : cancer_stage_diagnosis_ssa_low_burden.csv_clean
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden.csv_clean
CSV lu : generate_dataset (2).py_clean
CSV lu : cancer_survival_afcrn_high_burden.csv_clean
CSV lu : cancer_survival_afcrn_low_burden.csv_clean
CSV lu : cancer_survival_afcrn_moderate_burden.csv_clean
CSV lu : dataset_infos.json_clean
CSV lu : datad.csv_clean
CSV lu : dataf1.csv_clean
CSV lu : medquad.csv_clean
CSV lu : cancer_qa_dataset_1000_clean.csv
CSV lu : cancer_qa_dataset_5000_clean.csv
CSV lu : silk-hq-lutwos9z_clean.txt
CSV lu : code-block-m2vhenll_clean.txt
CSV lu : kt_clean.txt
CSV lu : index-ivzj8m6u_clean.txt
CSV lu : product-variants-ga945uk2_clean.txt
CSV lu : code-block-editor-pane-fzo1sbww_clean.txt
CSV lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean.txt
CSV lu : root-mn12m92t_clean.txt
CSV lu : conversation-small-1rwf4ooe_clean.txt
CSV lu : writing-block-editor-j0pgo4i4_clean.txt
CSV lu : table-components-ca43bz4f_clean.txt
CSV lu : ansi-1f6vhsjh_clean.txt
CSV lu : bb140dcc-565b-4572-aa9e-53f02d96d04a_clean.txt
CSV lu : js_clean.txt
CSV lu : saved_resource_clean.txt
CSV lu : DATTASET_clean.txt
CSV lu : test-00000-of-00001-1fb925721582029b_clean.txt
CSV lu : train-00000-of-00001-c0696c2b7ee38eb5_clean.txt
CSV lu : test_clean.csv
CSV lu : train_clean.csv
JSON lu : conversaciones_cancer_clean.json
JSON lu : conversaciones_cancer (2)_clean.json
JSON lu : conversaciones_cancer (3)_clean.json
CSV lu : Regenerated_Lung_Cancer_QA_Dataset_clean.csv
CSV lu : train-00000-of-00001_clean.txt
CSV lu : bone_cancer_samples_clean.csv
CSV lu : brain_tumour_samples_clean.csv
CSV lu : breast_cancer_samples_clean.csv
CSV lu : colon_cancer_samples_clean.csv
CSV lu : gastric_cancer_samples_clean.csv
CSV lu : kidney_cancer_samples_clean.csv
CSV lu : lung_cancer_samples_clean.csv
CSV lu : ovarian_cancer_samples_clean.csv
CSV lu : prostate_cancer_samples_clean.csv
CSV lu : skin_cancer_samples_clean.csv
CSV lu : lung_cancer_clean_5K_clean.txt
CSV lu : train-00002-of-00004_clean.txt
CSV lu : train-00003-of-00004_clean.txt
CSV lu : train-00000-of-00004_clean.txt
CSV lu : train-00000-of-00001 (3)_clean.txt
CSV lu : train-00000-of-00001 (2)_clean.txt
CSV lu : cancer-risk-factors_clean.csv
CSV lu : cancer_clean.csv
CSV lu : med_clean.csv
CSV lu : inca-donnees-mco-10.2025_clean.txt
CSV lu : inca-donnees-smr-10.2025_clean.txt
CSV lu : inca-donnees-had-10.2025_clean.txt
JSON lu : synthetic_structured_clean.json
JSON lu : synthetic_unstructured_clean.json
CSV lu : train-00000-of-00001 (6)_clean.txt
CSV lu : generate_dataset_clean.txt
CSV lu : cancer_risk_factors_steps_moderate_burden_clean.csv
CSV lu : cancer_risk_factors_steps_low_burden_clean.csv
CSV lu : cancer_risk_factors_steps_high_burden_clean.csv
CSV lu : cancer_treatment_patterns_high_burden_clean.csv
CSV lu : cancer_treatment_patterns_low_burden_clean.csv
CSV lu : cancer_treatment_patterns_moderate_burden_clean.csv
CSV lu : cancer_stage_diagnosis_ssa_high_burden_clean.csv
CSV lu : cancer_stage_diagnosis_ssa_low_burden_clean.csv
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden_clean.csv
CSV lu : generate_dataset (2)_clean.txt
CSV lu : cancer_survival_afcrn_high_burden_clean.csv
CSV lu : cancer_survival_afcrn_low_burden_clean.csv
CSV lu : cancer_survival_afcrn_moderate_burden_clean.csv
JSON lu : dataset_infos_clean.json
CSV lu : datad_clean.csv
CSV lu : dataf1_clean.csv
CSV lu : medquad_clean.csv
CSV lu : cancer_qa_dataset_1000_clean.txt
CSV lu : cancer_qa_dataset_5000_clean.txt
CSV lu : js_clean_clean.txt
CSV lu : dataset_clean.txt
CSV lu : test_clean.txt
CSV lu : train_clean.txt
CSV lu : conversaciones_cancer_clean.txt
CSV lu : conversaciones_cancer (2)_clean.txt
CSV lu : conversaciones_cancer (3)_clean.txt
CSV lu : Regenerated_Lung_Cancer_QA_Dataset_clean.txt
CSV lu : bone_cancer_samples_clean.txt
CSV lu : brain_tumour_samples_clean.txt
CSV lu : breast_cancer_samples_clean.txt
CSV lu : colon_cancer_samples_clean.txt
CSV lu : gastric_cancer_samples_clean.txt
CSV lu : kidney_cancer_samples_clean.txt
CSV lu : lung_cancer_samples_clean.txt
CSV lu : ovarian_cancer_samples_clean.txt
CSV lu : prostate_cancer_samples_clean.txt
CSV lu : skin_cancer_samples_clean.txt
CSV lu : cancer-risk-factors_clean.txt
CSV lu : cancer_clean.txt
CSV lu : med_clean.txt
CSV lu : synthetic_structured_clean.txt
CSV lu : synthetic_unstructured_clean.txt
CSV lu : cancer_risk_factors_steps_moderate_burden_clean.txt
CSV lu : cancer_risk_factors_steps_low_burden_clean.txt
CSV lu : cancer_risk_factors_steps_high_burden_clean.txt
CSV lu : cancer_treatment_patterns_high_burden_clean.txt
CSV lu : cancer_treatment_patterns_low_burden_clean.txt
CSV lu : cancer_treatment_patterns_moderate_burden_clean.txt
CSV lu : cancer_stage_diagnosis_ssa_high_burden_clean.txt
CSV lu : cancer_stage_diagnosis_ssa_low_burden_clean.txt
CSV lu : cancer_stage_diagnosis_ssa_moderate_burden_clean.txt
CSV lu : cancer_survival_afcrn_high_burden_clean.txt
CSV lu : cancer_survival_afcrn_low_burden_clean.txt
CSV lu : cancer_survival_afcrn_moderate_burden_clean.txt
CSV lu : dataset_infos_clean.txt
CSV lu : datad_clean.txt
CSV lu : dataf1_clean.txt
CSV lu : medquad_clean.txt
CSV lu : cancer_qa_dataset_1000_clean_clean.csv
CSV lu : cancer_qa_dataset_5000_clean_clean.csv
CSV lu : silk-hq-lutwos9z_clean_clean.txt
CSV lu : code-block-m2vhenll_clean_clean.txt
CSV lu : kt_clean_clean.txt
CSV lu : index-ivzj8m6u_clean_clean.txt
CSV lu : product-variants-ga945uk2_clean_clean.txt
CSV lu : code-block-editor-pane-fzo1sbww_clean_clean.txt
CSV lu : 1be4d668-cee5-4f1d-b5f6-cb0eb72c4c90_clean_clean.txt
CSV lu : root-mn12m92t_clean_clean.txt
CSV lu : conversation-small-1rwf4ooe_clean_clean.txt
CSV lu : writing-block-editor-j0pgo4i4_clean_clean.txt
CSV lu : table-components-ca43bz4f_clean_clean.txt
CSV lu : ansi-1f6vhsjh_clean_clean.txt
CSV lu : bb140dcc-565b-4572-aa9e-53f02d96d04a_clean_clean.txt
CSV lu : saved_resource_clean_clean.txt
CSV lu : DATTASET_clean_clean.txt
CSV lu : test-00000-of-00001-1fb925721582029b_clean_clean.txt
CSV lu : train-00000-of-00001-c0696c2b7ee38eb5_clean_clean.txt
CSV lu : test_clean_clean.csv
CSV lu : train_clean_clean.csv
JSON lu : conversaciones_cancer_clean_clean.json
JSON lu : conversaciones_cancer (2)_clean_clean.json
JSON lu : conversaciones_cancer (3)_clean_clean.json
CSV lu : Regenerated_Lung_Cancer_QA_Dataset_clean_clean.csv
CSV lu : train-00000-of-00001_clean_clean.txt
CSV lu : bone_cancer_samples_clean_clean.csv
CSV lu : brain_tumour_samples_clean_clean.csv
CSV lu : breast_cancer_samples_clean_clean.csv
CSV lu : colon_cancer_samples_clean_clean.csv
CSV lu : gastric_cancer_samples_clean_clean.csv
CSV lu : kidney_cancer_samples_clean_clean.csv
CSV lu : lung_cancer_samples_clean_clean.csv
CSV lu : ovarian_cancer_samples_clean_clean.csv
CSV lu : prostate_cancer_samples_clean_clean.csv
CSV lu : skin_cancer_samples_clean_clean.csv
CSV lu : lung_cancer_clean_5K_clean_clean.txt

In [ ]:
import os
import pandas as pd
import json
import xml.etree.ElementTree as ET

In [ ]:
folder3 = "/content/drive/MyDrive/datasetColab/data_csv.cancer_files"
files = os.listdir(folder3)

In [ ]:
output_file = "/content/drive/MyDrive/datasetColab/dataset3_clean.csv"

pd.DataFrame(columns=["question","answer"]).to_csv(output_file, index=False)

In [ ]:
for file in files:

    path = os.path.join(folder3, file)

    try:
        df = pd.read_csv(path, on_bad_lines='skip', engine='python')

        df = df.dropna()
        df = df.drop_duplicates()

        df.to_csv(output_file, mode='a', header=False, index=False)

        print("CSV traité :", file)

    except Exception as e:
        print("Erreur fichier :", file)

NameError: name 'folder3' is not defined

In [ ]:
import pandas as pd

dataset = pd.read_csv(
    output_file,
    engine="python",      # moteur plus tolérant
    on_bad_lines="skip"   # ignore les lignes cassées
)

print(dataset.shape)
dataset.head()

NameError: name 'output_file' is not defined

In [ ]:
print("Nombre de lignes :", len(dataset))
print(dataset.columns)

Nombre de lignes : 6277
Index(['question', 'answer'], dtype='object')

In [ ]:
dataset = dataset.dropna()
dataset = dataset.drop_duplicates()
dataset = dataset.reset_index(drop=True)

print("Dataset final :", len(dataset))

Dataset final : 6277

In [ ]:
dataset.to_csv("/content/drive/MyDrive/datasetColab/dataset3_clean_final.csv", index=False)

In [ ]:
import pandas as pd

dataset1 = pd.read_csv("/content/drive/MyDrive/datasetColab/cancer_dataset.csv")
dataset2 = pd.read_csv("/content/drive/MyDrive/datasetColab/cancer_dataset2.csv")
dataset3 = pd.read_csv("/content/drive/MyDrive/datasetColab/dataset3_clean_final.csv")

In [ ]:
print(dataset1.columns)
print(dataset2.columns)
print(dataset3.columns)

NameError: name 'dataset1' is not defined

In [ ]:
dataset_final = pd.concat([dataset1, dataset2, dataset3], ignore_index=True)

NameError: name 'dataset1' is not defined

In [ ]:
dataset_final = dataset_final.dropna()
dataset_final = dataset_final.drop_duplicates()
dataset_final = dataset_final.reset_index(drop=True)

NameError: name 'dataset_final' is not defined

In [ ]:
print("Nombre total de questions :", len(dataset_final))
dataset_final.head()

NameError: name 'dataset_final' is not defined

In [ ]:
dataset_final.to_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv", index=False)

NameError: name 'dataset_final' is not defined

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv")

print(len(dataset))
dataset.head()

6277

,question,answer
0,What is (are) Ovarian Germ Cell Tumors ?,Key Points\n - Ovarian germ...
1,What are the symptoms of Ovarian Germ Cell Tum...,Signs of ovarian germ cell tumor are swelling ...
2,How to diagnose Ovarian Germ Cell Tumors ?,"Tests that examine the ovaries, pelvic area, b..."
3,What is the outlook for Ovarian Germ Cell Tumo...,Certain factors affect prognosis (chance of re...
4,What are the stages of Ovarian Germ Cell Tumors ?,Key Points\n - After ovaria...

In [ ]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(dataset["question"])

In [ ]:
def chatbot(question):

    q_vec = vectorizer.transform([question])

    similarity = cosine_similarity(q_vec, X)

    best_index = similarity.argmax()

    best_score = similarity[0][best_index]

    if best_score < 0.2:
        return "I could not find a good answer."

    return dataset.iloc[best_index]["answer"]

In [ ]:
print(chatbot("What is cancer"))
print(chatbot("Tell me about cancer"))
print(chatbot("What causes cancer"))

Lung cancer is a disease in which abnormal cells grow uncontrollably in the affected tissue. These cells can form a tumor and may spread to nearby tissues or other organs through the blood or lymphatic system if not treated early.
None
Lung cancer develops due to genetic mutations in cells. These mutations may be influenced by environmental factors, infections, radiation exposure, lifestyle habits, or inherited genetic changes.

In [ ]:
print(chatbot("What is lung cancer"))
print(chatbot("What causes lung cancer"))
print(chatbot("How does lung cancer develop"))
print(chatbot("Explain lung cancer"))

Lung cancer is a disease in which abnormal cells grow uncontrollably in the affected tissue. These cells can form a tumor and may spread to nearby tissues or other organs through the blood or lymphatic system if not treated early.
Lung cancer develops due to genetic mutations in cells. These mutations may be influenced by environmental factors, infections, radiation exposure, lifestyle habits, or inherited genetic changes.
Lung cancer can interfere with normal body functions by damaging tissues, affecting organs, and disrupting the body's ability to maintain normal physiological processes.
Lung cancer is a disease in which abnormal cells grow uncontrollably in the affected tissue. These cells can form a tumor and may spread to nearby tissues or other organs through the blood or lymphatic system if not treated early.

In [ ]:
print(chatbot("Tell me about lung cancer"))
print(chatbot("What are the symptoms of lung cancer"))
print(chatbot("How is lung cancer treated"))

Lung cancer is a disease in which abnormal cells grow uncontrollably in the affected tissue. These cells can form a tumor and may spread to nearby tissues or other organs through the blood or lymphatic system if not treated early.
Symptoms of lung cancer can vary but may include pain, fatigue, weight loss, lumps or swelling, bleeding, or changes in normal body functions depending on the organ affected.
Early stage lung cancer is often treated with surgery to remove the tumor and may also include radiation therapy or targeted treatments to prevent recurrence.

In [ ]:
!pip install SpeechRecognition
!pip install gTTS
!pip install pyaudio

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)
Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from gTTS) (2.32.4)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2026.2.25)
Collecting pyaudio
  Using cached PyAudio-0.2.14.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyaudio
  error: subprocess-exited-with-error

  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pyaudio (pyproject.toml) ... error
  ERROR: Failed building wheel for pyaudio
Failed to build pyaudio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyaudio)

In [ ]:
!pip install SpeechRecognition
!pip install gTTS

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)
Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from gTTS) (2.32.4)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2026.2.25)

In [ ]:
from gtts import gTTS
import os

response = chatbot("What is lung cancer")

print(response)

tts = gTTS(response)
tts.save("answer.mp3")

Lung cancer is a disease in which abnormal cells grow uncontrollably in the affected tissue. These cells can form a tumor and may spread to nearby tissues or other organs through the blood or lymphatic system if not treated early.

In [ ]:
import speech_recognition as sr

In [ ]:
!pip install SpeechRecognition
!pip install gTTS
!pip install wikipedia

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)
Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from gTTS) (2.32.4)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2026.2.25)
Requirement already satisfied: wikipedia in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)

In [ ]:
import speech_recognition as sr
from gtts import gTTS
from IPython.display import Audio
import wikipedia

In [ ]:
import pandas as pd

dataset = pd.read_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv")

print(len(dataset))
dataset.head()

6277

,question,answer
0,What is (are) Ovarian Germ Cell Tumors ?,Key Points\n - Ovarian germ...
1,What are the symptoms of Ovarian Germ Cell Tum...,Signs of ovarian germ cell tumor are swelling ...
2,How to diagnose Ovarian Germ Cell Tumors ?,"Tests that examine the ovaries, pelvic area, b..."
3,What is the outlook for Ovarian Germ Cell Tumo...,Certain factors affect prognosis (chance of re...
4,What are the stages of Ovarian Germ Cell Tumors ?,Key Points\n - After ovaria...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(dataset["question"])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def chatbot(question):

    q_vec = vectorizer.transform([question])

    similarity = cosine_similarity(q_vec, X)

    index = similarity.argmax()

    score = similarity[0][index]

    # seuil de confiance
    if score < 0.4:
        return None

    return dataset.iloc[index]["answer"]

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.26.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Collecting httpx<1,>=0.23.0 (from openai)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (2.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->openai)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 2.1 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 3.0 MB/s eta 0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: h11, httpcore, httpx
  Attempting uninstall: h11
    Found existing installation: h11 0.9.0
    Uninstalling h11-0.9.0:
      Successfully uninstalled h11-0.9.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 0.9.1
    Uninstalling httpcore-0.9.1:
      Successfully uninstalled httpcore-0.9.1
  Attempting uninstall: httpx
    Found existing installation: httpx 0.13.3
    Uninstalling httpx-0.13.3:
      Successfully uninstalled httpx-0.13.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googletrans 4.0.0rc1 requires httpx==0.13.3, but you have httpx 0.28.1 which is incompatible.
Successfully installed h11-0.16.0 httpcore-1.0.9 httpx-0.28.1

In [ ]:
from openai import OpenAI

client = OpenAI(api_key="TA_CLE_API")

def search_gpt(question):

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {"role": "system", "content": "You are a medical assistant that answers questions about cancer."},
            {"role": "user", "content": question}
        ]
    )

    return response.choices[0].message.content

ImportError: cannot import name 'BaseTransport' from 'httpx' (/usr/local/lib/python3.12/dist-packages/httpx/__init__.py)

In [ ]:
text = "What causes lung cancer"

answer = chatbot(text)

if answer is None:
    answer = search_gpt(text)

print(answer)

NotFittedError: The TF-IDF vectorizer is not fitted

In [ ]:
from openai import OpenAI

client = OpenAI(api_key="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")

ImportError: cannot import name 'BaseTransport' from 'httpx' (/usr/local/lib/python3.12/dist-packages/httpx/__init__.py)

In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

In [ ]:
import requests

In [ ]:
def search_internet(question):

    url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + question.replace(" ", "_")

    try:
        response = requests.get(url)
        data = response.json()

        return data["extract"]

    except:
        return "Sorry, I could not find an answer online."

In [ ]:
text = input("Enter your question: ")

answer = chatbot(text)

if answer is None:
    answer = search_internet(text)

print("Answer:", answer)

Enter your question: c'est quoi le cancer

NotFittedError: The TF-IDF vectorizer is not fitted

In [ ]:
!pip install langdetect
!pip install googletrans==4.0.0-rc1

Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: googletrans==4.0.0-rc1 in /usr/local/lib/python3.12/dist-packages (4.0.0rc1)
Requirement already satisfied: httpx==0.13.3 in /usr/local/lib/python3.12/dist-packages (from googletrans==4.0.0-rc1) (0.13.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2026.2.25)
Requirement already satisfied: hstspreload in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2025.1.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in /usr/local/lib/python3.12/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.0)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.12/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.12/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)

In [ ]:
!pip install langdetect
!pip install deep-translator

Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)

In [ ]:
from langdetect import detect
from deep_translator import GoogleTranslator

In [ ]:
def detect_language(text):
    return detect(text)

In [ ]:
def translate_to_english(text):
    return GoogleTranslator(source='auto', target='en').translate(text)

In [ ]:
def translate_answer(answer, lang):
    return GoogleTranslator(source='en', target=lang).translate(answer)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv")

In [ ]:
import pandas as pd

dataset = pd.read_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv")

print(dataset.head())

                                            question  \
0           What is (are) Ovarian Germ Cell Tumors ?
1  What are the symptoms of Ovarian Germ Cell Tum...
2         How to diagnose Ovarian Germ Cell Tumors ?
3  What is the outlook for Ovarian Germ Cell Tumo...
4  What are the stages of Ovarian Germ Cell Tumors ?

                                              answer
0  Key Points\n                    - Ovarian germ...
1  Signs of ovarian germ cell tumor are swelling ...
2  Tests that examine the ovaries, pelvic area, b...
3  Certain factors affect prognosis (chance of re...
4  Key Points\n                    - After ovaria...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(dataset["question"])

NameError: name 'dataset' is not defined

In [ ]:

from difflib import get_close_matches

def chatbot(question):

    questions = dataset["question"].tolist()

    match = get_close_matches(question, questions, n=1, cutoff=0.3)

    if match:
        answer = dataset[dataset["question"] == match[0]]["answer"].values[0]
        return answer

    return None

In [ ]:
question = "What is ovarian germ cell tumor"

print(chatbot(question))

NameError: name 'chatbot' is not defined

In [ ]:
import requests

def search_internet(question):

    try:
        # simplifier la question
        keywords = question.lower().replace("what is", "").replace("c'est quoi", "").replace("define", "")
        keywords = keywords.strip()

        # recherche wikipedia
        search_url = "https://en.wikipedia.org/w/api.php"

        params = {
            "action": "query",
            "list": "search",
            "srsearch": keywords,
            "format": "json"
        }

        response = requests.get(search_url, params=params)
        data = response.json()

        title = data["query"]["search"][0]["title"]

        # récupérer résumé
        summary_url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + title

        response = requests.get(summary_url)
        summary = response.json()

        return summary["extract"]

    except:
        return "Désolé, je n'ai pas trouvé de réponse en ligne."

In [ ]:
question = input("Enter your question: ")

lang = detect_language(question)

question_en = translate_to_english(question)

answer = chatbot(question_en)

if answer is None:
    answer = search_internet(question_en)

final_answer = translate_answer(answer, lang)

print("Answer:", final_answer)

Enter your question: c'est quoi cancer

NameError: name 'detect_language' is not defined

In [ ]:
!pip install wikipedia

Requirement already satisfied: wikipedia in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)

In [ ]:
import wikipedia

In [ ]:
import wikipedia

def search_wikipedia(question):

    search_url = "https://en.wikipedia.org/w/api.php"

    params = {
        "action": "query",
        "list": "search",
        "srsearch": question,
        "format": "json"
    }

    r = requests.get(search_url, params=params)
    data = r.json()

    if len(data["query"]["search"]) == 0:
        return None

    page_title = data["query"]["search"][0]["title"]

    summary_url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + page_title

    r2 = requests.get(summary_url)

    if r2.status_code == 200:
        return r2.json().get("extract")

    return None

In [ ]:
question = input("Enter your question: ")

lang = detect_language(question)

question_en = translate_to_english(question)

answer = chatbot(question_en)

if answer is None:
    answer = search_internet(question_en)

# limiter la taille du texte
answer = answer[:1000]

final_answer = translate_answer(answer, lang)

print("Answer:", final_answer)

KeyboardInterrupt: Interrupted by user

In [ ]:
!pip install SpeechRecognition
!pip install gTTS

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)
Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from gTTS) (2.32.4)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2026.2.25)

In [ ]:
import speech_recognition as sr
from gtts import gTTS
from IPython.display import Audio

In [ ]:
import speech_recognition as sr

recognizer = sr.Recognizer()

with sr.AudioFile("question.mp3") as source:
    audio = recognizer.record(source)

text = recognizer.recognize_google(audio)

print("Question :", text)

FileNotFoundError: [Errno 2] No such file or directory: 'question.mp3'

In [ ]:
from IPython.display import Javascript, display
from google.colab.output import eval_js
from base64 import b64decode

def record_audio(filename="question.wav"):

    js = Javascript("""
    async function recordAudio() {
      const stream = await navigator.mediaDevices.getUserMedia({audio:true});
      const recorder = new MediaRecorder(stream);
      const chunks = [];

      recorder.ondataavailable = e => chunks.push(e.data);

      recorder.start();

      await new Promise(resolve => setTimeout(resolve, 5000));

      recorder.stop();

      await new Promise(resolve => recorder.onstop = resolve);

      const blob = new Blob(chunks);

      const reader = new FileReader();
      reader.readAsDataURL(blob);

      await new Promise(resolve => reader.onloadend = resolve);

      return reader.result;
    }
    recordAudio();
    """)

    display(js)

    audio = eval_js("recordAudio()")
    audio = b64decode(audio.split(',')[1])

    with open(filename, "wb") as f:
        f.write(audio)

    print("Audio enregistré :", filename)

In [ ]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.12.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.135.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.5.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.0)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.5)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.41.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (2.10)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.3.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Collecting click>=8.2.1 (from typer<1.0,>=0.12->gradio)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.3/108.3 kB 2.3 MB/s eta 0:00:00
Installing collected packages: click
  Attempting uninstall: click
    Found existing installation: click 8.1.8
    Uninstalling click-8.1.8:
      Successfully uninstalled click-8.1.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gtts 2.5.4 requires click<8.2,>=7.1, but you have click 8.3.1 which is incompatible.
Successfully installed click-8.3.1

In [ ]:
!pip install SpeechRecognition

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)

In [ ]:
from IPython.display import Javascript, display
from google.colab.output import eval_js
from base64 import b64decode

def record_audio(filename="question.wav"):

    js = Javascript("""
    async function recordAudio(){
      const stream = await navigator.mediaDevices.getUserMedia({audio:true});
      const recorder = new MediaRecorder(stream);
      const chunks = [];
      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();
      await new Promise(resolve => setTimeout(resolve, 5000));
      recorder.stop();
      await new Promise(resolve => recorder.onstop = resolve);
      const blob = new Blob(chunks);
      const reader = new FileReader();
      reader.readAsDataURL(blob);
      await new Promise(resolve => reader.onloadend = resolve);
      return reader.result;
    }
    """)

    display(js)

    audio = eval_js("recordAudio()")
    audio = b64decode(audio.split(',')[1])

    with open(filename,"wb") as f:
        f.write(audio)

    print("Audio enregistré :", filename)

In [ ]:
!pip install SpeechRecognition pydub

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (0.25.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)

In [ ]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def record_audio(filename="question.wav", seconds=5):
    display(Javascript("""
    async function recordAudio(sec){
      const stream = await navigator.mediaDevices.getUserMedia({audio:true});
      const recorder = new MediaRecorder(stream);
      const chunks = [];
      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();
      await new Promise(resolve => setTimeout(resolve, sec*1000));
      recorder.stop();
      await new Promise(resolve => recorder.onstop = resolve);
      const blob = new Blob(chunks);
      const reader = new FileReader();
      reader.readAsDataURL(blob);
      await new Promise(resolve => reader.onloadend = resolve);
      return reader.result;
    }
    """))

    audio = eval_js(f"recordAudio({seconds})")
    audio = b64decode(audio.split(',')[1])

    with open(filename, "wb") as f:
        f.write(audio)

    print("Audio enregistré :", filename)

In [ ]:
record_audio()

Audio enregistré : question.wav

In [ ]:
record_audio()

Audio enregistré : question.wav

In [ ]:
from IPython.display import Audio
Audio("question.wav")

In [ ]:
!apt-get install ffmpeg

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
!ffmpeg -i question.wav question_fixed.wav

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'question.wav':
  Metadata:
    encoder         : Chrome
  Duration: 00:00:04.56, start: 0.000000, bitrate: 131 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, mono, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'question_fixed.wav':
  Metadata:
    ISFT            : Lavf58.76.100
  Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      encoder         : Lavc58.134.100 pcm_s16le
size=     433kB time=00:00:04.55 bitrate= 778.3kbits/s speed=74.9x
video:0kB audio:433kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.017587%

In [ ]:
import speech_recognition as sr

recognizer = sr.Recognizer()

with sr.AudioFile("question_fixed.wav") as source:
    audio = recognizer.record(source)

text = recognizer.recognize_google(audio)

print("Question:", text)

UnknownValueError:

In [ ]:
!ls

answer.mp3  drive  question_fixed.wav  question.wav  sample_data

In [ ]:
record_audio()

Audio enregistré : question.wav

In [ ]:
from IPython.display import Audio
Audio("question.wav")

In [ ]:
!ffmpeg -y -i question.wav -acodec pcm_s16le -ar 16000 question_fixed.wav

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'question.wav':
  Metadata:
    encoder         : Chrome
  Duration: 00:00:04.86, start: 0.000000, bitrate: 130 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, mono, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'question_fixed.wav':
  Metadata:
    ISFT            : Lavf58.76.100
  Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default)
    Metadata:
      encoder         : Lavc58.134.100 pcm_s16le
size=     154kB time=00:00:04.91 bitrate= 256.2kbits/s speed= 190x
video:0kB audio:154kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.049543%

In [ ]:
import speech_recognition as sr

recognizer = sr.Recognizer()

with sr.AudioFile("question_fixed.wav") as source:
    audio = recognizer.record(source)

try:
    text = recognizer.recognize_google(audio)
    print("Question:", text)

except sr.UnknownValueError:
    print("Je n'ai pas compris la voix")

except sr.RequestError:
    print("Erreur connexion Google")

Je n'ai pas compris la voix

In [ ]:
from IPython.display import Javascript
from google.colab import output
from base64 import b64decode

def record_audio():
  display(Javascript("""
    async function record() {
      const stream = await navigator.mediaDevices.getUserMedia({audio:true});
      const recorder = new MediaRecorder(stream);
      let chunks = [];

      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();

      await new Promise(resolve => setTimeout(resolve, 5000));

      recorder.stop();

      return await new Promise(resolve => {
        recorder.onstop = async () => {
          const blob = new Blob(chunks);
          const buffer = await blob.arrayBuffer();
          const base64 = btoa(
            new Uint8Array(buffer)
              .reduce((data, byte) => data + String.fromCharCode(byte), '')
          );
          resolve(base64);
        };
      });
    }
  """))

  audio = output.eval_js("record()")
  audio_bytes = b64decode(audio)

  with open("audio.webm", "wb") as f:
      f.write(audio_bytes)

  print("Audio enregistré : audio.webm")

record_audio()

Audio enregistré : audio.webm

In [ ]:
record_audio()

Audio enregistré : audio.webm

In [ ]:
!apt-get install ffmpeg

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
!ffmpeg -i audio.webm audio.wav

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'audio.webm':
  Metadata:
    encoder         : Chrome
  Duration: 00:00:05.52, start: 0.000000, bitrate: 130 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, mono, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'audio.wav':
  Metadata:
    ISFT            : Lavf58.76.100
  Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      encoder         : Lavc58.134.100 pcm_s16le
size=     523kB time=00:00:05.51 bitrate= 776.5kbits/s speed= 243x
video:0kB audio:523kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.014561%

In [ ]:
!pip install openai-whisper
!apt-get install ffmpeg

Requirement already satisfied: openai-whisper in /usr/local/lib/python3.12/dist-packages (20250625)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.12.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.10.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (4.67.3)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (3.6.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.25.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2025.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper) (3.0.3)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
record_audio()

Audio enregistré : audio.webm

In [ ]:
import whisper

In [ ]:
model = whisper.load_model("base")

In [ ]:
result = model.transcribe("audio.wav")

question = result["text"]

print("Utilisateur :", question)

/usr/local/lib/python3.12/dist-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

Utilisateur :

In [ ]:
record_audio()

Audio enregistré

In [ ]:
!pip install assemblyai
!pip install elevenlabs
!pip install transformers
!pip install pandas
!pip install requests
!pip install deep-translator
!pip install langdetect

Collecting assemblyai
  Downloading assemblyai-0.54.1-py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: httpx>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (0.28.1)
Requirement already satisfied: typing-extensions>=3.7 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (4.15.0)
Requirement already satisfied: websockets>=11.0 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (15.0.1)
Requirement already satisfied: pydantic>=1.10.17 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (2.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.19.0->assemblyai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (0.4.2)
Downloading assemblyai-0.54.1-py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.3/54.3 kB 3.4 MB/s eta 0:00:00
Installing collected packages: assemblyai
Successfully installed assemblyai-0.54.1
Collecting elevenlabs
  Downloading elevenlabs-2.38.1-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: httpx>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.12.3)
Requirement already satisfied: pydantic-core>=2.18.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.41.4)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.32.4)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (4.15.0)
Requirement already satisfied: websockets>=11.0 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (15.0.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.21.2->elevenlabs) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->elevenlabs) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->elevenlabs) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->elevenlabs) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->elevenlabs) (2.5.0)
Downloading elevenlabs-2.38.1-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 16.4 MB/s eta 0:00:00
Installing collected packages: elevenlabs
Successfully installed elevenlabs-2.38.1
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Collecting click>=8.2.1 (from typer->huggingface-hub<2.0,>=1.3.0->transformers)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.3/108.3 kB 3.1 MB/s eta 0:00:00
Installing collected packages: click
  Attempting uninstall: click
    Found existing installation: click 8.1.8
    Uninstalling click-8.1.8:
      Successfully uninstalled click-8.1.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gtts 2.5.4 requires click<8.2,>=7.1, but you have click 8.3.1 which is incompatible.
Successfully installed click-8.3.1
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 13.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=683943e6a85aeebc8253ad62134c813a256efe4d84db0114bf45f7e53a5ac43e
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
ASSEMBLYAI_API_KEY = "9aa1ae6ebef74d64becda97f20f0b68b"
ELEVENLABS_API_KEY = "sk_381f36ea4f490a668d106aac45ba28536f0652db1c79be15"

In [ ]:
import assemblyai as aai

aai.settings.api_key = ASSEMBLYAI_API_KEY

def speech_to_text_api(audio_file):

    config = aai.TranscriptionConfig(
        speech_models=["universal"]
    )

    transcriber = aai.Transcriber()

    transcript = transcriber.transcribe(
        audio_file,
        config=config
    )

    return transcript.text

In [ ]:
!pip install vosk

Collecting vosk
  Downloading vosk-0.3.45-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from vosk) (2.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vosk) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vosk) (4.67.3)
Collecting srt (from vosk)
  Downloading srt-3.5.3.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: websockets in /usr/local/lib/python3.12/dist-packages (from vosk) (15.0.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->vosk) (3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (2026.2.25)
Downloading vosk-0.3.45-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 50.0 MB/s eta 0:00:00
Building wheels for collected packages: srt
  Building wheel for srt (setup.py) ... done
  Created wheel for srt: filename=srt-3.5.3-py3-none-any.whl size=22427 sha256=7bf86eaa20bb02eb9fbab51943d9d96fce8b86e6fbc9634f4aff4512ade403d9
  Stored in directory: /root/.cache/pip/wheels/7e/75/5b/e1d5c3756631e4bda806f6cc9640153b39484bb6f7b0b8def3
Successfully built srt
Installing collected packages: srt, vosk
Successfully installed srt-3.5.3 vosk-0.3.45

In [ ]:
import vosk
import json
import wave

def speech_to_text_free(audio_file):

    model = vosk.Model("vosk-model-small-en-us")

    wf = wave.open(audio_file, "rb")

    rec = vosk.KaldiRecognizer(model, wf.getframerate())

    text = ""

    while True:
        data = wf.readframes(4000)
        if len(data) == 0:
            break

        if rec.AcceptWaveform(data):
            result = json.loads(rec.Result())
            text += result["text"]

    return text

In [ ]:
!apt-get install ffmpeg -y
!pip install sounddevice

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Collecting sounddevice
  Downloading sounddevice-0.5.5-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: cffi in /usr/local/lib/python3.12/dist-packages (from sounddevice) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi->sounddevice) (3.0)
Downloading sounddevice-0.5.5-py3-none-any.whl (32 kB)
Installing collected packages: sounddevice
Successfully installed sounddevice-0.5.5

In [ ]:
!wget https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip
!unzip vosk-model-small-en-us-0.15.zip

--2026-03-12 17:18:48--  https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip
Resolving alphacephei.com (alphacephei.com)... 188.40.21.16, 2a01:4f8:13a:279f::2
Connecting to alphacephei.com (alphacephei.com)|188.40.21.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41205931 (39M) [application/zip]
Saving to: ‘vosk-model-small-en-us-0.15.zip’

vosk-model-small-en 100%[===================>]  39.30M  20.2MB/s    in 1.9s

2026-03-12 17:18:51 (20.2 MB/s) - ‘vosk-model-small-en-us-0.15.zip’ saved [41205931/41205931]

Archive:  vosk-model-small-en-us-0.15.zip
   creating: vosk-model-small-en-us-0.15/
   creating: vosk-model-small-en-us-0.15/am/
  inflating: vosk-model-small-en-us-0.15/am/final.mdl
   creating: vosk-model-small-en-us-0.15/graph/
  inflating: vosk-model-small-en-us-0.15/graph/disambig_tid.int
  inflating: vosk-model-small-en-us-0.15/graph/HCLr.fst
  inflating: vosk-model-small-en-us-0.15/graph/Gr.fst
   creating: vosk-model-small-en-us-0.15/graph/phones/
  inflating: vosk-model-small-en-us-0.15/graph/phones/word_boundary.int
   creating: vosk-model-small-en-us-0.15/conf/
  inflating: vosk-model-small-en-us-0.15/conf/model.conf
  inflating: vosk-model-small-en-us-0.15/conf/mfcc.conf
   creating: vosk-model-small-en-us-0.15/ivector/
  inflating: vosk-model-small-en-us-0.15/ivector/splice.conf
  inflating: vosk-model-small-en-us-0.15/ivector/final.dubm
  inflating: vosk-model-small-en-us-0.15/ivector/global_cmvn.stats
  inflating: vosk-model-small-en-us-0.15/ivector/final.ie
  inflating: vosk-model-small-en-us-0.15/ivector/online_cmvn.conf
  inflating: vosk-model-small-en-us-0.15/ivector/final.mat
  inflating: vosk-model-small-en-us-0.15/README

In [ ]:
import vosk
import json
import wave

model = vosk.Model("vosk-model-small-en-us-0.15")

wf = wave.open("audio.wav","rb")

rec = vosk.KaldiRecognizer(model, wf.getframerate())

while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break

    if rec.AcceptWaveform(data):
        result = json.loads(rec.Result())
        print(result["text"])

In [ ]:
!pip install assemblyai
!pip install elevenlabs
!pip install vosk
!pip install deepspeech
!pip install TTS
!pip install pandas
!pip install requests
!pip install deep-translator
!pip install langdetect
!apt-get install ffmpeg -y

Requirement already satisfied: assemblyai in /usr/local/lib/python3.12/dist-packages (0.54.1)
Requirement already satisfied: httpx>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (0.28.1)
Requirement already satisfied: typing-extensions>=3.7 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (4.15.0)
Requirement already satisfied: websockets>=11.0 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (15.0.1)
Requirement already satisfied: pydantic>=1.10.17 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (2.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.19.0->assemblyai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (0.4.2)
Requirement already satisfied: elevenlabs in /usr/local/lib/python3.12/dist-packages (2.38.1)
Requirement already satisfied: httpx>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.12.3)
Requirement already satisfied: pydantic-core>=2.18.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.41.4)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.32.4)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (4.15.0)
Requirement already satisfied: websockets>=11.0 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (15.0.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.21.2->elevenlabs) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->elevenlabs) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->elevenlabs) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->elevenlabs) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->elevenlabs) (2.5.0)
Requirement already satisfied: vosk in /usr/local/lib/python3.12/dist-packages (0.3.45)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from vosk) (2.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vosk) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vosk) (4.67.3)
Requirement already satisfied: srt in /usr/local/lib/python3.12/dist-packages (from vosk) (3.5.3)
Requirement already satisfied: websockets in /usr/local/lib/python3.12/dist-packages (from vosk) (15.0.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->vosk) (3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (2026.2.25)
ERROR: Could not find a version that satisfies the requirement deepspeech (from versions: none)
ERROR: No matching distribution found for deepspeech
ERROR: Ignored the following versions that require a different python version: 0.0.10.2 Requires-Python >=3.6.0, <3.9; 0.0.10.3 Requires-Python >=3.6.0, <3.9; 0.0.11 Requires-Python >=3.6.0, <3.9; 0.0.12 Requires-Python >=3.6.0, <3.9; 0.0.13.1 Requires-Python >=3.6.0, <3.9; 0.0.13.2 Requires-Python >=3.6.0, <3.9; 0.0.14.1 Requires-Python >=3.6.0, <3.9; 0.0.15 Requires-Python >=3.6.0, <3.9; 0.0.15.1 Requires-Python >=3.6.0, <3.9; 0.0.9 Requires-Python >=3.6.0, <3.9; 0.0.9.1 Requires-Python >=3.6.0, <3.9; 0.0.9.2 Requires-Python >=3.6.0, <3.9; 0.0.9a10 Requires-Python >=3.6.0, <3.9; 0.0.9a9 Requires-Python >=3.6.0, <3.9; 0.1.0 Requires-Python >=3.6.0, <3.10; 0.1.1 Requires-Python >=3.6.0, <3.10; 0.1.2 Requires-Python >=3.6.0, <3.10; 0.1.3 Requires-Python >=3.6.0, <3.10; 0.10.0 Requires-Python >=3.7.0, <3.11; 0.10.1 Requires-Python >=3.7.0, <3.11; 0.10.2 Requires-Python >=3.7.0, <3.11; 0.11.0 Requires-Python >=3.7.0, <3.11; 0.11.1 Requires-Python >=3.7.0, <3.11; 0.12.0 Requires-Python >=3.7.0, <3.11; 0.13.0 Requires-Python >=3.7.0, <3.11; 0.13.1 Requires-Python >=3.7.0, <3.11; 0.13.2 Requires-Python >=3.7.0, <3.11; 0.13.3 Requires-Python >=3.7.0, <3.11; 0.14.0 Requires-Python >=3.7.0, <3.11; 0.14.2 Requires-Python >=3.7.0, <3.11; 0.14.3 Requires-Python >=3.7.0, <3.11; 0.15.0 Requires-Python >=3.9.0, <3.12; 0.15.1 Requires-Python >=3.9.0, <3.12; 0.15.2 Requires-Python >=3.9.0, <3.12; 0.15.4 Requires-Python >=3.9.0, <3.12; 0.15.5 Requires-Python >=3.9.0, <3.12; 0.15.6 Requires-Python >=3.9.0, <3.12; 0.16.0 Requires-Python >=3.9.0, <3.12; 0.16.1 Requires-Python >=3.9.0, <3.12; 0.16.3 Requires-Python >=3.9.0, <3.12; 0.16.4 Requires-Python >=3.9.0, <3.12; 0.16.5 Requires-Python >=3.9.0, <3.12; 0.16.6 Requires-Python >=3.9.0, <3.12; 0.17.0 Requires-Python >=3.9.0, <3.12; 0.17.1 Requires-Python >=3.9.0, <3.12; 0.17.2 Requires-Python >=3.9.0, <3.12; 0.17.4 Requires-Python >=3.9.0, <3.12; 0.17.5 Requires-Python >=3.9.0, <3.12; 0.17.6 Requires-Python >=3.9.0, <3.12; 0.17.7 Requires-Python >=3.9.0, <3.12; 0.17.8 Requires-Python >=3.9.0, <3.12; 0.17.9 Requires-Python >=3.9.0, <3.12; 0.18.0 Requires-Python >=3.9.0, <3.12; 0.18.1 Requires-Python >=3.9.0, <3.12; 0.18.2 Requires-Python >=3.9.0, <3.12; 0.19.0 Requires-Python >=3.9.0, <3.12; 0.19.1 Requires-Python >=3.9.0, <3.12; 0.2.0 Requires-Python >=3.6.0, <3.10; 0.2.1 Requires-Python >=3.6.0, <3.10; 0.2.2 Requires-Python >=3.6.0, <3.10; 0.20.0 Requires-Python >=3.9.0, <3.12; 0.20.1 Requires-Python >=3.9.0, <3.12; 0.20.2 Requires-Python >=3.9.0, <3.12; 0.20.3 Requires-Python >=3.9.0, <3.12; 0.20.4 Requires-Python >=3.9.0, <3.12; 0.20.5 Requires-Python >=3.9.0, <3.12; 0.20.6 Requires-Python >=3.9.0, <3.12; 0.21.0 Requires-Python >=3.9.0, <3.12; 0.21.1 Requires-Python >=3.9.0, <3.12; 0.21.2 Requires-Python >=3.9.0, <3.12; 0.21.3 Requires-Python >=3.9.0, <3.12; 0.22.0 Requires-Python >=3.9.0, <3.12; 0.3.0 Requires-Python >=3.6.0, <3.10; 0.3.1 Requires-Python >=3.6.0, <3.10; 0.4.0 Requires-Python >=3.6.0, <3.10; 0.4.1 Requires-Python >=3.6.0, <3.10; 0.4.2 Requires-Python >=3.6.0, <3.10; 0.5.0 Requires-Python >=3.6.0, <3.10; 0.6.0 Requires-Python >=3.6.0, <3.10; 0.6.1 Requires-Python >=3.6.0, <3.10; 0.6.2 Requires-Python >=3.6.0, <3.10; 0.7.0 Requires-Python >=3.7.0, <3.11; 0.7.1 Requires-Python >=3.7.0, <3.11; 0.8.0 Requires-Python >=3.7.0, <3.11; 0.9.0 Requires-Python >=3.7.0, <3.11
ERROR: Could not find a version that satisfies the requirement TTS (from versions: none)
ERROR: No matching distribution found for TTS
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
!pip install assemblyai
!pip install elevenlabs
!pip install vosk
!pip install pandas
!pip install requests
!pip install deep-translator
!pip install langdetect
!apt-get install ffmpeg -y

Requirement already satisfied: assemblyai in /usr/local/lib/python3.12/dist-packages (0.54.1)
Requirement already satisfied: httpx>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (0.28.1)
Requirement already satisfied: typing-extensions>=3.7 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (4.15.0)
Requirement already satisfied: websockets>=11.0 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (15.0.1)
Requirement already satisfied: pydantic>=1.10.17 in /usr/local/lib/python3.12/dist-packages (from assemblyai) (2.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.19.0->assemblyai) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.19.0->assemblyai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.10.17->assemblyai) (0.4.2)
Requirement already satisfied: elevenlabs in /usr/local/lib/python3.12/dist-packages (2.38.1)
Requirement already satisfied: httpx>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.12.3)
Requirement already satisfied: pydantic-core>=2.18.2 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.41.4)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (2.32.4)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (4.15.0)
Requirement already satisfied: websockets>=11.0 in /usr/local/lib/python3.12/dist-packages (from elevenlabs) (15.0.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.21.2->elevenlabs) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.21.2->elevenlabs) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->elevenlabs) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->elevenlabs) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->elevenlabs) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->elevenlabs) (2.5.0)
Requirement already satisfied: vosk in /usr/local/lib/python3.12/dist-packages (0.3.45)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from vosk) (2.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vosk) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vosk) (4.67.3)
Requirement already satisfied: srt in /usr/local/lib/python3.12/dist-packages (from vosk) (3.5.3)
Requirement already satisfied: websockets in /usr/local/lib/python3.12/dist-packages (from vosk) (15.0.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->vosk) (3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vosk) (2026.2.25)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
ASSEMBLYAI_API_KEY = "9aa1ae6ebef74d64becda97f20f0b68b"
ELEVENLABS_API_KEY = "sk_381f36ea4f490a668d106aac45ba28536f0652db1c79be15"

In [ ]:
answer = search_dataset(question_en)

if not answer:
    answer = search_wikipedia(question_en)

if not answer:
    answer = "Je n'ai pas trouvé la réponse."

In [ ]:
import requests

def search_api(question):

    try:

        headers = {
            "User-Agent": "CancerVoiceAssistant/1.0 (student project)"
        }

        search_url = "https://en.wikipedia.org/w/api.php"

        params = {
            "action": "query",
            "list": "search",
            "srsearch": question,
            "format": "json"
        }

        r = requests.get(search_url, params=params, headers=headers)

        data = r.json()

        if len(data["query"]["search"]) == 0:
            return None

        page_title = data["query"]["search"][0]["title"]

        summary_url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + page_title

        r2 = requests.get(summary_url, headers=headers)

        if r2.status_code == 200:
            return r2.json().get("extract")

    except:
        return None

    return None

In [ ]:
import assemblyai as aai

aai.settings.api_key = ASSEMBLYAI_API_KEY

def speech_to_text_api(audio_file):

    config = aai.TranscriptionConfig(
        speech_models=["universal"]
    )

    transcriber = aai.Transcriber()

    transcript = transcriber.transcribe(audio_file, config=config)

    return transcript.text

NameError: name 'ASSEMBLYAI_API_KEY' is not defined

In [ ]:
import vosk
import json
import wave

def speech_to_text_free(audio_file):

    model = vosk.Model("vosk-model-small-en-us-0.15")

    wf = wave.open(audio_file, "rb")

    rec = vosk.KaldiRecognizer(model, wf.getframerate())

    text = ""

    while True:

        data = wf.readframes(4000)

        if len(data) == 0:
            break

        if rec.AcceptWaveform(data):

            result = json.loads(rec.Result())

            text += result["text"]

    return text

In [ ]:
from elevenlabs.client import ElevenLabs
from elevenlabs import play

client = ElevenLabs(api_key=ELEVENLABS_API_KEY)

from elevenlabs.client import ElevenLabs
from IPython.display import Audio, display

client = ElevenLabs(api_key=ELEVENLABS_API_KEY)

def text_to_speech_api(text):

    audio = client.text_to_speech.convert(
        voice_id="21m00Tcm4TlvDq8ikWAM",
        model_id="eleven_multilingual_v2",
        text=text
    )

    with open("response.mp3","wb") as f:
        for chunk in audio:
            f.write(chunk)

    display(Audio("response.mp3"))

In [ ]:
!pip install gTTS

Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from gTTS) (2.32.4)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2026.2.25)

In [ ]:
from gtts import gTTS
from IPython.display import Audio, display

def text_to_speech_api_free(text, lang):

    if lang == "fr":
        tts_lang = "fr"
    elif lang == "ar":
        tts_lang = "ar"
    else:
        tts_lang = "en"

    tts = gTTS(text=text, lang=tts_lang)

    tts.save("response.mp3")

    display(Audio("response.mp3"))

In [ ]:
from langdetect import detect

def detect_language(text):

    try:
        lang = detect(text)

        if lang.startswith("fr"):
            return "fr"
        elif lang.startswith("ar"):
            return "ar"
        else:
            return "en"

    except:
        return "en"

In [ ]:
from deep_translator import GoogleTranslator
def translate_to_english(text, lang):

    if lang == "en":
        return text

    return GoogleTranslator(source=lang, target="en").translate(text)

In [ ]:
from elevenlabs.client import ElevenLabs
from IPython.display import Audio, display

client = ElevenLabs(api_key=ELEVENLABS_API_KEY)

def text_to_speech_api(text):

    audio = client.text_to_speech.convert(
        voice_id="21m00Tcm4TlvDq8ikWAM",
        model_id="eleven_multilingual_v2",
        text=text
    )

    with open("response.mp3","wb") as f:
        for chunk in audio:
            f.write(chunk)

    display(Audio("response.mp3"))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive

'Colab Notebooks'   datasetColab  'projets de la base de donner'

In [ ]:
!ls /content/drive/MyDrive/datasetColab

 1_CancerGov_QA
'archive (13)'
 cancer_dataset2_clean_clean_clean_clean.csv
 cancer_dataset2_clean_clean_clean.csv
 cancer_dataset2_clean_clean.csv
 cancer_dataset2_clean.csv
 cancer_dataset2.csv
 cancer_dataset_clean_clean_clean_clean.csv
 cancer_dataset_clean_clean_clean.csv
 cancer_dataset_clean_clean.csv
 cancer_dataset_clean.csv
 cancer_dataset.csv
 data_csv.cancer_files
 dataset3_clean_clean_clean_clean_clean.csv
 dataset3_clean_clean_clean_clean.csv
 dataset3_clean_clean_clean.csv
 dataset3_clean_clean.csv
 dataset3_clean.csv
 dataset3_clean_final_clean_clean_clean_clean.csv
 dataset3_clean_final_clean_clean_clean.csv
 dataset3_clean_final_clean_clean.csv
 dataset3_clean_final_clean.csv
 dataset3_clean_final.csv
 final_dataset_clean_clean_clean_clean.csv
 final_dataset_clean_clean_clean.csv
 final_dataset_clean_clean.csv
 final_dataset_clean.csv
 final_dataset.csv

In [ ]:
def search_dataset(question):

    question = question.lower()

    for i in range(len(dataset)):

        q = str(dataset["question"][i]).lower()

        if question in q:
            return dataset["answer"][i]

    return None

In [ ]:
def translate_back(text, lang):

    if lang == "en":
        return text

    return GoogleTranslator(source="en", target=lang).translate(text)

In [ ]:
from IPython.display import Javascript, display
from google.colab import output
from base64 import b64decode

def record_audio(seconds=5):

    display(Javascript(f"""
    async function record() {{
      const stream = await navigator.mediaDevices.getUserMedia({{audio:true}});
      const recorder = new MediaRecorder(stream);
      let chunks = [];

      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();

      await new Promise(resolve => setTimeout(resolve, {seconds*1000}));

      recorder.stop();

      return await new Promise(resolve => {{
        recorder.onstop = async () => {{
          const blob = new Blob(chunks);
          const buffer = await blob.arrayBuffer();
          const base64 = btoa(
            new Uint8Array(buffer)
              .reduce((data, byte) => data + String.fromCharCode(byte), '')
          );
          resolve(base64);
        }};
      }});
    }}
    record();
    """))

    audio = output.eval_js("record()")
    audio_bytes = b64decode(audio)

    with open("audio.webm","wb") as f:
        f.write(audio_bytes)

In [ ]:
from deep_translator import GoogleTranslator

def translate_to_english(text, lang):

    if lang == "en":
        return text

    try:
        return GoogleTranslator(source='auto', target='en').translate(text)
    except:
        return text

In [ ]:
from deep_translator import GoogleTranslator

def translate_back(text, lang):

    if lang == "en":
        return text

    try:
        return GoogleTranslator(source='auto', target=lang).translate(text)
    except:
        return text

In [ ]:
from langdetect import detect

def detect_language(text):

    try:
        lang = detect(text)

        if lang.startswith("fr"):
            return "fr"
        elif lang.startswith("ar"):
            return "ar"
        else:
            return "en"

    except:
        return "en"

In [ ]:
import vosk
import wave
import json

def speech_to_text_free(audio_file):

    model = vosk.Model("vosk-model-small-en-us-0.15")

    wf = wave.open(audio_file, "rb")

    rec = vosk.KaldiRecognizer(model, wf.getframerate())

    text = ""

    while True:
        data = wf.readframes(4000)
        if len(data) == 0:
            break
        if rec.AcceptWaveform(data):
            result = json.loads(rec.Result())
            text += result.get("text","")

    result = json.loads(rec.FinalResult())
    text += result.get("text","")

    return text

In [ ]:
import pandas as pd

dataset_path = "/content/drive/MyDrive/datasetColab/final_dataset.csv"

dataset = pd.read_csv(dataset_path)

def search_dataset(question):

    matches = dataset[dataset["question"].str.contains(question, case=False, na=False)]

    if len(matches) > 0:
        return matches.iloc[0]["answer"]

    return None

In [ ]:
print(dataset.head())

                                            question  \
0           What is (are) Ovarian Germ Cell Tumors ?
1  What are the symptoms of Ovarian Germ Cell Tum...
2         How to diagnose Ovarian Germ Cell Tumors ?
3  What is the outlook for Ovarian Germ Cell Tumo...
4  What are the stages of Ovarian Germ Cell Tumors ?

                                              answer
0  Key Points\n                    - Ovarian germ...
1  Signs of ovarian germ cell tumor are swelling ...
2  Tests that examine the ovaries, pelvic area, b...
3  Certain factors affect prognosis (chance of re...
4  Key Points\n                    - After ovaria...

In [ ]:
import requests

def search_api(question):

    try:
        headers = {
            "User-Agent": "CancerVoiceAssistant/1.0"
        }

        # recherche sur Wikipedia
        search_url = "https://en.wikipedia.org/w/api.php"

        params = {
            "action": "query",
            "list": "search",
            "srsearch": question,
            "format": "json"
        }

        r = requests.get(search_url, params=params, headers=headers)
        data = r.json()

        if len(data["query"]["search"]) == 0:
            return None

        # récupérer le titre de la page
        page_title = data["query"]["search"][0]["title"]

        # récupérer le résumé
        summary_url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + page_title

        r2 = requests.get(summary_url, headers=headers)

        if r2.status_code == 200:
            return r2.json().get("extract")

    except:
        return None

    return None

In [ ]:
from deep_translator import GoogleTranslator

def translate_back(text, lang):

    if lang == "en":
        return text

    try:
        return GoogleTranslator(source='auto', target=lang).translate(text)
    except:
        return text

In [ ]:
import assemblyai as aai

aai.settings.api_key = "TA_CLE_API_ASSEMBLYAI"

def speech_to_text_api(audio_file):

    transcriber = aai.Transcriber()

    transcript = transcriber.transcribe(audio_file)

    return transcript.text

In [ ]:
print("Fonction chargée")

Fonction chargée

In [ ]:
import assemblyai as aai

aai.settings.api_key = "TA_API_KEY"

def speech_to_text_api(audio_file):
    transcriber = aai.Transcriber()
    transcript = transcriber.transcribe(audio_file)
    return transcript.text

In [ ]:
from langdetect import detect

def detect_language(text):
    return detect(text)

In [ ]:
from deep_translator import GoogleTranslator

def translate_to_english(text, lang):

    if lang == "en":
        return text

    return GoogleTranslator(source=lang, target="en").translate(text)


def translate_back(text, lang):

    if lang == "en":
        return text

    return GoogleTranslator(source="en", target=lang).translate(text)

In [ ]:
def search_dataset(question):

    matches = dataset[dataset["question"].str.contains(question, case=False, na=False)]

    if len(matches) > 0:
        return matches.iloc[0]["answer"]

    return None

In [ ]:
!pip install openai-whisper
!apt-get install ffmpeg

Collecting openai-whisper
  Downloading openai_whisper-20250625.tar.gz (803 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 9.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.12.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.10.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (4.67.3)
Collecting triton>=2 (from openai-whisper)
  Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.25.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2025.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper) (3.0.3)
Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 1.6 MB/s eta 0:00:00
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20250625-py3-none-any.whl size=803979 sha256=2cb8cebf5a13d7c2dc686b3b19cee7cdfa953fd77720b4a6fe8e0ade142a857d
  Stored in directory: /root/.cache/pip/wheels/61/d2/20/09ec9bef734d126cba375b15898010b6cc28578d8afdde5869
Successfully built openai-whisper
Installing collected packages: triton, openai-whisper
Successfully installed openai-whisper-20250625 triton-3.6.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
import whisper

model = whisper.load_model("base")

result = model.transcribe("audio.wav")

text = result["text"]

print("Utilisateur :", text)

100%|███████████████████████████████████████| 139M/139M [00:01<00:00, 97.7MiB/s]
/usr/local/lib/python3.12/dist-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

Utilisateur :  1.5g of sugar 1.5g of sugar 1.5g of sugar 1.5g of salt 1.5g of salt

In [ ]:
pip install SpeechRecognition

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)

In [ ]:
pip install pyaudio

Collecting pyaudio
  Downloading PyAudio-0.2.14.tar.gz (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 kB 759.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (pyproject.toml) ... done
  Created wheel for pyaudio: filename=pyaudio-0.2.14-cp312-cp312-linux_x86_64.whl size=68667 sha256=cd247383574b13c4d0d07a11eb2b3213f94231080372c703d0786d87b4815429
  Stored in directory: /root/.cache/pip/wheels/68/c7/33/c6a6b210cb5819ec5c219928c794a447742a7d86d21c0b92e6
Successfully built pyaudio
Installing collected packages: pyaudio
Successfully installed pyaudio-0.2.14

In [ ]:
import speech_recognition as sr

recognizer = sr.Recognizer()

with sr.AudioFile("audio.wav") as source:
    audio = recognizer.record(source)

try:
    text = recognizer.recognize_google(audio)
    print("Texte utilisateur :", text)

except sr.UnknownValueError:
    print("L'audio n'a pas été compris")

except sr.RequestError:
    print("Erreur de connexion à l'API")

L'audio n'a pas été compris

In [ ]:
!pip install SpeechRecognition
!pip install pydub

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (0.25.1)

In [ ]:
from IPython.display import Javascript
from google.colab import output
from base64 import b64decode

RECORD = """
const sleep = time => new Promise(resolve => setTimeout(resolve, time))
const b2text = blob => new Promise(resolve => {
  const reader = new FileReader()
  reader.onloadend = e => resolve(reader.result.split(',')[1])
  reader.readAsDataURL(blob)
})

var record = async () => {
  const stream = await navigator.mediaDevices.getUserMedia({audio:true})
  const recorder = new MediaRecorder(stream)
  let chunks = []

  recorder.ondataavailable = e => chunks.push(e.data)

  recorder.start()
  await sleep(5000)
  recorder.stop()

  await new Promise(resolve => recorder.onstop = resolve)

  const blob = new Blob(chunks)
  const text = await b2text(blob)

  return text
}
record()
"""

audio = output.eval_js(RECORD)

with open("audio.wav","wb") as f:
    f.write(b64decode(audio))

In [ ]:
!apt-get install ffmpeg
!pip install pydub SpeechRecognition

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (0.25.1)
Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)

In [ ]:
from pydub import AudioSegment

audio = AudioSegment.from_file("audio.wav")
audio.export("audio_fixed.wav", format="wav")

In [ ]:
import speech_recognition as sr

r = sr.Recognizer()

with sr.AudioFile("audio_fixed.wav") as source:
    audio = r.record(source)

try:
    text = r.recognize_google(audio, language="fr-FR")
    print("Texte :", text)

except sr.UnknownValueError:
    print("Le système n'a pas compris l'audio")

Texte : what is cancer what is cancer

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv")

print(data.head())

                                            question  \
0           What is (are) Ovarian Germ Cell Tumors ?
1  What are the symptoms of Ovarian Germ Cell Tum...
2         How to diagnose Ovarian Germ Cell Tumors ?
3  What is the outlook for Ovarian Germ Cell Tumo...
4  What are the stages of Ovarian Germ Cell Tumors ?

                                              answer
0  Key Points\n                    - Ovarian germ...
1  Signs of ovarian germ cell tumor are swelling ...
2  Tests that examine the ovaries, pelvic area, b...
3  Certain factors affect prognosis (chance of re...
4  Key Points\n                    - After ovaria...

In [ ]:
question_user = text.lower()

import difflib

questions = data["question"].astype(str).tolist()

match = difflib.get_close_matches(question_user, questions, n=1, cutoff=0.5)

if match:

    row = data[data["question"] == match[0]]

    response = row.iloc[0]["answer"]

else:

    response = None

In [ ]:
!pip install wikipedia

Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=8d4998f38ff98fc6324eb63576f7c1f2f0654574cfba1bb32de03818478a31b6
  Stored in directory: /root/.cache/pip/wheels/63/47/7c/a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0

In [ ]:
!pip install langdetect

Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)

In [ ]:
from langdetect import detect

lang = detect(text)

print("Langue détectée :", lang)

Langue détectée : en

In [ ]:
if lang == "fr":
    url = "https://fr.wikipedia.org/w/api.php"

elif lang == "ar":
    url = "https://ar.wikipedia.org/w/api.php"

else:
    url = "https://en.wikipedia.org/w/api.php"

In [ ]:
import requests
from langdetect import detect

lang = detect(text)

if lang == "fr":
    url = "https://fr.wikipedia.org/w/api.php"
elif lang == "ar":
    url = "https://ar.wikipedia.org/w/api.php"
else:
    url = "https://en.wikipedia.org/w/api.php"

params = {
    "action": "query",
    "list": "search",
    "srsearch": text,
    "format": "json"
}

headers = {
    "User-Agent": "CancerVoiceAssistant/1.0"
}

r = requests.get(url, params=params, headers=headers)

data = r.json()

response = data["query"]["search"][0]["snippet"]

print("Réponse :", response)

Réponse : <span class="searchmatch">Cancer</span> <span class="searchmatch">is</span> a group of diseases involving uncontrolled cell growth typically resulting in tumors with the potential to invade or spread to other parts of

In [ ]:
!pip install SpeechRecognition

Requirement already satisfied: SpeechRecognition in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from SpeechRecognition) (4.15.0)

In [ ]:
!pip install langdetect

Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)

In [ ]:
!pip install gTTS

Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from gTTS) (2.32.4)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->gTTS) (2026.2.25)

In [ ]:
!pip install wikipedia

Requirement already satisfied: wikipedia in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)

In [ ]:
!apt-get install ffmpeg

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
print("Réponse :", response)

from gtts import gTTS
from IPython.display import Audio

tts = gTTS(text=response, lang=lang)
tts.save("response.mp3")

Audio("response.mp3")

Réponse : <span class="searchmatch">Cancer</span> <span class="searchmatch">is</span> a group of diseases involving uncontrolled cell growth typically resulting in tumors with the potential to invade or spread to other parts of

In [ ]:
!pip install sounddevice scipy

Requirement already satisfied: sounddevice in /usr/local/lib/python3.12/dist-packages (0.5.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: cffi in /usr/local/lib/python3.12/dist-packages (from sounddevice) (2.0.0)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy) (2.0.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi->sounddevice) (3.0)

In [ ]:
!apt-get install ffmpeg

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
from IPython.display import Javascript, display
from google.colab import output
from base64 import b64decode

def record_audio(filename="audio.wav", seconds=5):

    display(Javascript("""
    async function recordAudio(){
      const stream = await navigator.mediaDevices.getUserMedia({audio:true});
      const recorder = new MediaRecorder(stream);
      const chunks = [];
      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();

      await new Promise(resolve => setTimeout(resolve, 5000));

      recorder.stop();
      await new Promise(resolve => recorder.onstop = resolve);

      const blob = new Blob(chunks);
      const arrayBuffer = await blob.arrayBuffer();
      const base64 = btoa(
        new Uint8Array(arrayBuffer)
          .reduce((data, byte) => data + String.fromCharCode(byte), '')
      );

      google.colab.kernel.invokeFunction('notebook.save_audio',[base64],{});
    }
    recordAudio();
    """))

    def save_audio(base64_audio):
        audio_bytes = b64decode(base64_audio)
        with open(filename, "wb") as f:
            f.write(audio_bytes)

    output.register_callback('notebook.save_audio', save_audio)

record_audio()

In [ ]:
r = sr.Recognizer()

with sr.AudioFile("audio_fixed.wav") as source:
    audio = r.record(source)

try:
    text = r.recognize_google(audio, language="fr-FR")
except sr.UnknownValueError:
    print("Audio non compris")
    text = ""
except sr.RequestError:
    print("Erreur API")
    text = ""

print("Utilisateur :", text)

Audio non compris
Utilisateur :

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks', 'projets de la base de donner', 'datasetColab']

In [ ]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks', 'projets de la base de donner', 'datasetColab']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/datasetColab/final_dataset.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install openai-whisper pandas wikipedia langdetect deep-translator gTTS
!apt-get -y install ffmpeg

Requirement already satisfied: openai-whisper in /usr/local/lib/python3.12/dist-packages (20250625)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.12.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.10.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (4.67.3)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wikipedia) (2.32.4)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->wikipedia) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.2.25)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2025.11.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.25.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper) (3.0.3)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=34be20f583c88539362e8f58ebe3846ed2d53c4185ffdca203fc89e72099e3b2
  Stored in directory: /root/.cache/pip/wheels/63/47/7c/a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

print(os.listdir("/content/drive/MyDrive"))

['projets de la base de donner', 'Colab Notebooks', 'datasetColab']

In [ ]:
# -----------------------
# INSTALLATION
# -----------------------
!pip install openai-whisper pandas langdetect deep-translator gTTS requests
!apt-get -y install ffmpeg


# -----------------------
# IMPORTS
# -----------------------
import whisper
import pandas as pd
import requests
from langdetect import detect
from deep_translator import GoogleTranslator
from gtts import gTTS
from IPython.display import Audio, display, Javascript
from google.colab import output
from base64 import b64decode
import subprocess
import re


# -----------------------
# GROQ API KEY
# -----------------------
GROQ_API_KEY = "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"


# -----------------------
# DATASET
# -----------------------
PATH_CSV="/content/drive/MyDrive/datasetColab/final_dataset.csv"

data = pd.read_csv(PATH_CSV).dropna(subset=["question","answer"])

questions = data["question"].str.lower().str.strip().tolist()
answers = data["answer"].tolist()


# -----------------------
# WHISPER MODEL
# -----------------------
model = whisper.load_model("small")


# -----------------------
# GROQ API
# -----------------------
def groq_api(query):

    url = "https://api.groq.com/openai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "llama-3.1-8b-instant",
        "messages": [
            {
                "role": "system",
                "content": "You are a scientific assistant. Give clear and short definitions."
            },
            {
                "role": "user",
                "content": query
            }
        ],
        "temperature": 0.2
    }

    r = requests.post(url, headers=headers, json=payload)

    if r.status_code == 200:
        result = r.json()
        return result["choices"][0]["message"]["content"]

    return "I could not find information."


# -----------------------
# RECORD AUDIO
# -----------------------
def record_audio(filename="audio.webm", duration=5):

    print("🎤 Parlez maintenant (5 secondes)...")

    display(Javascript(f"""
    async function recordAudio(){{
        const stream = await navigator.mediaDevices.getUserMedia({{audio:true}});
        const recorder = new MediaRecorder(stream);
        const chunks=[];

        recorder.ondataavailable=e=>chunks.push(e.data);
        recorder.start();

        await new Promise(resolve=>setTimeout(resolve,{duration}000));

        recorder.stop();

        return new Promise(resolve=>{{
            recorder.onstop=async()=>{{
                const blob=new Blob(chunks);
                const reader=new FileReader();
                reader.readAsDataURL(blob);
                reader.onloadend=()=>resolve(reader.result.split(',')[1]);
            }}
        }})
    }}
    """))

    audio = output.eval_js("recordAudio()")

    with open(filename,"wb") as f:
        f.write(b64decode(audio))

    return filename


# -----------------------
# RECORD AUDIO
# -----------------------
audio_file = record_audio()


# -----------------------
# CONVERT AUDIO
# -----------------------
subprocess.run([
"ffmpeg","-y",
"-i",audio_file,
"-ac","1",
"-ar","16000",
"audio.wav"
], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# -----------------------
# TRANSCRIPTION
# -----------------------
result = model.transcribe("audio.wav")

user_text = result["text"].strip()

print("📝 Question :", user_text)


# -----------------------
# PROCESS QUESTION
# -----------------------
if not user_text:

    final_text = "Je n'ai pas compris la question."

else:

    # language detection
    try:
        user_lang = detect(user_text)
    except:
        user_lang = "fr"

    if user_lang.startswith("fr"):
        user_lang = "fr"
    elif user_lang.startswith("ar"):
        user_lang = "ar"
    elif user_lang.startswith("en"):
        user_lang = "en"
    else:
        user_lang = "fr"


    # translate to english
    try:
        query_en = GoogleTranslator(source='auto', target='en').translate(user_text)
        query_en = query_en.lower().strip()
    except:
        query_en = user_text.lower().strip()


    # -----------------------
    # DATASET EXACT SEARCH
    # -----------------------
    if query_en in questions:

        print("📚 Answer from dataset")

        index = questions.index(query_en)
        response_en = answers[index]

    else:

        print("🤖 Answer from Groq AI")

        response_en = groq_api(query_en)


    # -----------------------
    # TRANSLATE RESPONSE
    # -----------------------
    try:
        final_text = GoogleTranslator(source='en', target=user_lang).translate(response_en)
    except:
        final_text = response_en


# -----------------------
# PRINT RESPONSE
# -----------------------
print("🤖 Réponse :", final_text)


# -----------------------
# AUDIO RESPONSE
# -----------------------

# nettoyer le texte
clean_text = re.sub(r"[*#\-]", "", final_text)

tts = gTTS(text=clean_text, lang=user_lang)
tts.save("response.mp3")

display(Audio("response.mp3", autoplay=True))

Requirement already satisfied: openai-whisper in /usr/local/lib/python3.12/dist-packages (20250625)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: gTTS in /usr/local/lib/python3.12/dist-packages (2.5.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.12.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.10.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (4.67.3)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: click<8.2,>=7.1 in /usr/local/lib/python3.12/dist-packages (from gTTS) (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2025.11.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.25.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper) (3.0.3)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
🎤 Parlez maintenant (5 secondes)...

/usr/local/lib/python3.12/dist-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

📝 Question : C'est quoi la définition de cancer ?
🤖 Answer from Groq AI
🤖 Réponse : Le cancer est une croissance incontrôlée de cellules anormales dans le corps, envahissant souvent les tissus environnants et pouvant se propager à d’autres parties du corps.